// THE ACADEMIC TIMES - Master Portal Data & Media Literacy Knowledge Base
// Contains all 12 articles, 3 distinct daily editions, and high-school media literacy references.

const MEDIA_RESOURCES = [
  {
    key: "time",
    name: "TIME Magazine (米国・オピニオン週刊誌)",
    country: "USA",
    founded: "1923年",
    stance: "教養・分析・中道リベラル",
    examSignificance: "早慶・上智・東大など難関大入試長文で過去30年間最頻出。感情論を排し、認知心理学や統計データに基づいた論証型エッセイの最高峰。",
    whyHighSchoolersMustKnow: "ニュースに興味がない高校生でも、TIME誌の『日常の当たり前を疑うエッセイ』を読むだけで、自由英作文や小論文で問われる論理構成（主張→具体例→反論の考慮）が自然と身につきます。",
    sampleTopics: "デジタル社会の孤独、退屈と創造性、労働観の変容、宇宙探査の意義",
    badge: "頻出度: Sランク（文理共通）"
  },
  {
    key: "the-times",
    name: "The Times (英国・本格高級日刊紙)",
    country: "UK",
    founded: "1785年",
    stance: "伝統的保守・格調高い言論",
    examSignificance: "世界標準フォント『Times New Roman』の発祥元。英国議会政治、法制度、司法判断の最高権威。東大・京大・一橋の要約・下線部和訳の定番出典。",
    whyHighSchoolersMustKnow: "簡潔で引き締まった格調高い文体（The Times Style）は、文法的に厳密な複文（倒置・同格・分詞構文）の宝庫。正確な英文解釈力を鍛えるのに最適です。",
    sampleTopics: "国家安全保障、司法審査、王室・憲法制度、大英帝国の歴史的検証",
    badge: "頻出度: Sランク（難関国公立2次）"
  },
  {
    key: "the-guardian",
    name: "The Guardian (英国・国際的リベラル高級紙)",
    country: "UK",
    founded: "1821年",
    stance: "中道リベラル・環境・調査報道",
    examSignificance: "世界で最も読まれるオンライン高級紙の一つ。環境問題、人権、AI倫理、社会的不平等など『現代の重要課題』を最も深く追究するメディア。",
    whyHighSchoolersMustKnow: "全記事が完全無料公開されているため、高校生の独習に最適。現代社会・倫理の教科書に載っているようなテーマの最前線を生きた英語で学べます。",
    sampleTopics: "気候変動、AI診断と親の同意、貧困と教育格差、監視資本主義批判",
    badge: "頻出度: Sランク（自由英作文・小論文直結）"
  },
  {
    key: "nature",
    name: "Nature & Nature Medicine (国際総合科学学術誌)",
    country: "International (UK/USA)",
    founded: "1869年",
    stance: "学術査読・世界的科学権威",
    examSignificance: "医学部・理系難関大の入試長文で圧倒的な出題率。近年は文系入試でも『認知バイアス』『行動経済学』『腸内細菌と心理』などで頻出。",
    whyHighSchoolersMustKnow: "『仮説→実験手法→結果→考察』という科学的思考の定型フォーマットを英語で追えるようになり、共通テストの図表・実験読解にも直結します。",
    sampleTopics: "50歳未満の大腸がん増加、マイクロプラスチックの体内動態、海洋生態系の崩壊",
    badge: "頻出度: Sランク（医学部・難関理系必修）"
  },
  {
    key: "reuters",
    name: "Reuters & AP News (世界二大国際通信社)",
    country: "UK / USA",
    founded: "1851年 / 1846年",
    stance: "完全中立・客観的事実報道",
    examSignificance: "世界中のテレビ局や大手新聞が記事を買って配信する『一次ソース中の一次ソース』。記者の主観を徹底排除した5W1Hの簡潔な構文。",
    whyHighSchoolersMustKnow: "感情や煽りのない『何が起きたのか』という骨太の事実把握力を養成できるため、共通テスト第5問・第6問のような情報処理型速読に絶大な効果があります。",
    sampleTopics: "米軍爆撃機再配置、国際条約交渉、サプライチェーン寸断、感染症速報",
    badge: "頻出度: Aランク（速読・事実把握力）"
  },
  {
    key: "ft",
    name: "Financial Times (FT) & The Sunday Times",
    country: "UK",
    founded: "1888年",
    stance: "国際経済・市場・政策分析",
    examSignificance: "国際金融・世界経済・税制改革の最前線。慶應経済・法、早稲田政経、東大・一橋の社会科学系長文で頻出する本格派メディア。",
    whyHighSchoolersMustKnow: "反語表現（Rhetorical Questions）や対比構文（not A but B）など、評論文の核心を突くレトリックが凝縮。経済・政治に苦手意識がある高校生でも社会の仕組みがクリアに見えてきます。",
    sampleTopics: "相続税改革と世代間格差、地方起業の規制緩和、新興国債務、通貨政策",
    badge: "頻出度: Aランク（社会科学・経済学部志望）"
  },
  {
    key: "science-mag",
    name: "Science & MIT Technology Review",
    country: "USA",
    founded: "1880年 / 1899年",
    stance: "先端的科学技術・未来社会",
    examSignificance: "米国科学振興協会（AAAS）発行の世界的科学雑誌とMITのテクノロジー誌。文理融合型の最新科学知見（生成AI、生命工学等）が平易な英語で解説される。",
    whyHighSchoolersMustKnow: "AIやバイオテクノロジーの進歩が人間の倫理や過去の進化史をどう書き換えているかを学べ、文理を問わず大学の志望理由書や面接の知識武装になります。",
    sampleTopics: "生成ニューラルネットワークによる古生物生体復元、量子暗号、合成生物学",
    badge: "頻出度: Aランク（文理融合・SFC・理工）"
  },
  {
    key: "the-conversation",
    name: "The Conversation & Project Syndicate",
    country: "International",
    founded: "2011年 / 1995年",
    stance: "研究者直接執筆・オープンアカデミア",
    examSignificance: "大学教授や研究者自らが、高校生〜一般読者に向けて最新研究を解説する教育的メディア。難関大入試長文で近年出題が急激に増加中。",
    whyHighSchoolersMustKnow: "専門用語が巧みに日常語に言い換えられているため、難関大入試のパラフレーズ（同義語言い換え）問題や内容一致問題の対策に最適です。",
    sampleTopics: "都市における微小な対人交流の幸福感、行動経済学のナッジ理論、教育格差",
    badge: "頻出度: 注目度急上昇ランク"
  },
  {
    key: "jiji",
    name: "Jiji Press (時事通信 / Japan's Independent News Agency)",
    country: "Japan",
    founded: "1945年",
    stance: "独立・公正・客観的報道",
    examSignificance: "日本を代表する総合通信社。政治・経済・政策報道に強みを持ち、国内外の重要ニュースを事実に基づいて正確かつ迅速に配信。論説・政策決定の分析に最適。",
    whyHighSchoolersMustKnow: "半導体国家戦略や国際地政学、経済安全保障など、大学入試・小論文で問われる日本の政策課題の背景知識を学べます。日本語の確かな情報を学術英語に転換する訓練に最適です。",
    sampleTopics: "半導体国産化戦略（ラピダス）、経済安全保障、サプライチェーン再編、国際通商政策",
    badge: "新規追加: 国内最高峰通信社（政策・経済）"
  },
  {
    key: "yahoo",
    name: "Yahoo! News Japan (Yahoo!ニュース / Specialized Features)",
    country: "Japan",
    founded: "1996年",
    stance: "多様な論点・国民的課題・教育福祉",
    examSignificance: "日本最大級のニュースプラットフォーム。多角的な視点や有識者解説（オーサー記事）が充実し、身近な社会問題や教育現場の実態に鋭く切り込む。",
    whyHighSchoolersMustKnow: "デジタル端末の普及に伴う学校現場の課題（置き勉・ランドセルの重さ）など、高校生自身が当事者である教育・社会問題を英語で表現・議論する絶好の題材が揃っています。",
    sampleTopics: "学校教育のデジタル化と身体負荷、GIGAスクール構想、少子高齢化と地域コミュニティ",
    badge: "新規追加: 国民的メディア（教育・社会課題）"
  },
  {
    key: "getnews",
    name: "GetNews Japan (ガジェット通信 / Tech & Entertainment)",
    country: "Japan",
    founded: "2008年",
    stance: "ガジェット・ポップカルチャー・デジタルライフ",
    examSignificance: "最新デジタル機器、スマートグラス、AIサービス、エンターテインメント文化をいち早く発信。テクノロジーが日常生活や若者文化に与える影響を先取りするメディア。",
    whyHighSchoolersMustKnow: "ARグラスや生成AIの普及とプライバシー倫理など、高校生にとってワクワクする最新ガジェットを通じて、未来社会のルール作りを英語で考える力を養えます。",
    sampleTopics: "AIスマートグラスとプライバシー保護、次世代ウェアラブル端末、デジタルエンタメ倫理",
    badge: "新規追加: エンタメ・ガジェット（新ジャンル）"
  }
];

const ALL_ARTICLES = [
  {
    slug: "headphones-in-public",
    category: "culture",
    category_label: "COGNITIVE PSYCHOLOGY & CULTURE",
    date: "2026-10-06",
    title: "The Case Against Wearing Headphones in Public: Reclaiming the Power of Reverie",
    headline_ja: "公共空間でイヤホンを外す効用：失われた「物思い（白昼夢）」を取り戻す",
    subhead: "米週刊誌TIME掲載のエッセイ。常時接続と孤独、創造性を育む退屈の価値を認知心理学で徹底解説。",
    lead_snippet: "英国通信庁（Ofcom）の最新調査では成人の93%が毎週音声メディアに浸り、1日の中の「すべての静寂の合間」が埋め尽くされている。公共空間でイヤホンを外したジャーナリストの気づきから、認知心理学が解き明かす「意図せぬ白昼夢」と「見知らぬ他者との偶発的交流」がもたらす計り知れない効用を精読する。",
    source_name: "TIME Magazine (Oct 5, 2026 / Meehika Barua)",
    source_media_key: "time",
    source_url: "https://time.com/7023812/case-against-wearing-headphones-in-public/",
    path: "culture/headphones-in-public/index.html",
    image: "https://static.time.com/v3/assets/bltea6093859af6183b/blt96d6f358ea9d50b0/6abfba6215869b08e9e95a32/headphones.jpg?branch=production&width=1200&quality=80&auto=webp"
  },
  {
    slug: "jeffrey-archer-obituary",
    category: "culture",
    category_label: "CULTURE & OBITUARY",
    date: "2026-10-01",
    title: "Jeffrey Archer, Bestselling Novelist and Political Figure, Dies Aged 86",
    headline_ja: "ベストセラー作家で元政治家のジェフリー・アーチャー氏が86歳で死去",
    subhead: "3億部を売り上げた英国大衆文学の巨匠の軌跡。伝記・文学論述における時制と修辞を学ぶ。",
    lead_snippet: "世界的ベストセラー『ケインとアベル』で知られる英国の小説家・政治家ジェフリー・アーチャー氏の生涯。栄光と服役、そして不屈の復活劇を英国高級紙の格調高い評伝英語で読み解く。",
    source_name: "The Times UK / The Guardian (Oct 1, 2026)",
    source_media_key: "the-times",
    source_url: "https://www.thetimes.co.uk/article/jeffrey-archer-obituary",
    path: "culture/jeffrey-archer-obituary/index.html",
    image: "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=1000&auto=format&fit=crop&q=80"
  },
  {
    slug: "air-defence-shield",
    category: "law",
    category_label: "LAW & NATIONAL SECURITY",
    date: "2026-10-05",
    title: "British Parliament Debates £10bn Integrated Air Defence Shield",
    headline_ja: "英国議会、100億ポンド規模の統合防空シールド配備をめぐり審議入り",
    subhead: "防衛装備調達の透明性と国家安全保障法制。財政民主主義の観点から法学英語を精読。",
    lead_snippet: "防空レーダー網と迎撃システムの刷新を巡る英国議会の白熱した討論。国家安全保障上の機密保持と公的資金の使途説明責任（accountability）という法哲学的ジレンマを検証する。",
    source_name: "Financial Times / The Times UK (Oct 5, 2026)",
    source_media_key: "ft",
    source_url: "https://www.ft.com/content/defence-procurement-uk-shield",
    path: "law/air-defence-shield/index.html",
    image: "https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=1000&auto=format&fit=crop&q=80"
  },
  {
    slug: "royal-security-judicial-review",
    category: "law",
    category_label: "LAW & CONSTITUTION",
    date: "2026-10-05",
    title: "King Will Not Fund Legal Challenge Against Security Withdrawal",
    headline_ja: "国王、公的警護打ち切りに対する法的異議申し立てへの資金拠出を拒否",
    subhead: "王室経費と公的警護権をめぐる司法審査（judicial review）の基本概念と行政法論述。",
    lead_snippet: "王室離脱後の公的警護費用をめぐる法廷闘争。税金による警護の妥当性と行政裁量権の限界を、英米法の最高裁判例のロジックから読み解く。",
    source_name: "The Telegraph / The Times UK (Oct 5, 2026)",
    source_media_key: "the-times",
    source_url: "https://www.telegraph.co.uk/royal-family/security-judicial-review",
    path: "law/royal-security-judicial-review/index.html",
    image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=1000&auto=format&fit=crop&q=80"
  },
  {
    slug: "ai-pediatric-diagnosis-consent",
    category: "law",
    category_label: "LAW & BIOETHICS",
    date: "2026-10-03",
    title: "High Court Weighs Parental Consent in AI-Driven Pediatric Diagnoses",
    headline_ja: "英高等法院、AIによる小児診療判断における親の同意権の範囲を審理",
    subhead: "AI医療判断と親の同意権。アルゴリズムの説明責任とインフォームド・コンセントの再定義。",
    lead_snippet: "小児疾患の早期発見においてAI診断アルゴリズムが医師の所見と食い違った場合、親の治療選択権はどう保護されるのか。英米法におけるギリック能力（Gillick competence）の現代的解釈。",
    source_name: "The Guardian / BMJ Health Tech (Oct 3, 2026)",
    source_media_key: "the-guardian",
    source_url: "https://www.theguardian.com/technology/ai-pediatric-diagnosis-court",
    path: "law/ai-pediatric-diagnosis-consent/index.html",
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=1000&auto=format&fit=crop&q=80"
  },
  {
    slug: "colorectal-cancer-under-50s",
    category: "science",
    category_label: "SCIENCE & MEDICINE",
    date: "2026-10-04",
    title: "Mystery Rise in Colorectal Cancer Rates Among Under-50s",
    headline_ja: "50歳未満における大腸がん罹患率の世界的急増：科学が追う環境要因の謎",
    subhead: "マイクロプラスチック、超加工食品、腸内細菌叢の変容。最新の医学疫学論文を平易に解説。",
    lead_snippet: "従来は高齢者特有とされていた大腸がんが若年層で急増している背景とは。超加工食品に含まれる乳化剤やマイクロプラスチックが生体組織に与える長期的影響を科学論文の論理展開で精読。",
    source_name: "Nature Medicine / BBC Health (Oct 4, 2026)",
    source_media_key: "nature",
    source_url: "https://www.nature.com/articles/nm-colorectal-cancer-trends",
    path: "science/colorectal-cancer-under-50s/index.html",
    image: "https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?w=1000&auto=format&fit=crop&q=80"
  },
  {
    slug: "generative-ai-paleontology",
    category: "science",
    category_label: "SCIENCE & COMPUTATIONAL BIOLOGY",
    date: "2026-10-03",
    title: "Generative Neural Networks Reconstruct Locomotion in Extinct Vertebrates",
    headline_ja: "生成ニューラルネットワーク、絶滅脊椎動物の運動メカニズムを生体復元",
    subhead: "化石の断片から生体運動を再現する最新ディープラーニング技術。仮説検証の英文法。",
    lead_snippet: "数千万年前に絶滅した生物の歩行速度や筋肉配置を、生成AIの物理シミュレーションによって再現。生物進化の謎を解き明かす先端テクノロジーの英語構文。",
    source_name: "Science / MIT Technology Review (Oct 3, 2026)",
    source_media_key: "science-mag",
    source_url: "https://www.science.org/doi/10.1126/science.paleo.genai",
    path: "science/generative-ai-paleontology/index.html",
    image: "https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=1000&auto=format&fit=crop&q=80"
  },
  {
    slug: "mediterranean-marine-heatwaves",
    category: "science",
    category_label: "SCIENCE & MARINE ECOLOGY",
    date: "2026-10-04",
    title: "Mediterranean Marine Heatwaves Threaten Deep-Water Coral Colonies",
    headline_ja: "地中海の海洋熱波、深海性サンゴ群集を直撃：深海生態系に迫る不可逆的危機",
    subhead: "海水温躍層の崩壊と生物多様性の損失。環境変動の因果関係構文と科学的ファクトチェック。",
    lead_snippet: "水面下数十メートルから百メートル以上の深海域にまで及ぶ未知の海洋熱波。光の届かない冷水域で数百年かけて成長する深海サンゴの大量死滅が警告する海洋生態系の危機。",
    source_name: "Reuters Science / Copernicus Climate Service (Oct 4, 2026)",
    source_media_key: "reuters",
    source_url: "https://www.reuters.com/business/environment/med-heatwaves-coral-reefs",
    path: "science/mediterranean-marine-heatwaves/index.html",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1000&auto=format&fit=crop&q=80"
  },
  {
    slug: "psychology-casual-encounters",
    category: "society",
    category_label: "SOCIETY & BEHAVIORAL SCIENCE",
    date: "2026-10-06",
    title: "The Psychology of Casual Encounters: Why Micro-Connections Boost Urban Well-Being",
    headline_ja: "偶然の出会いの心理学：見知らぬ人とのささやかな会話が都市の幸福感を高める理由",
    subhead: "シカゴ大学Epley教授の通勤実験とGranovetterの『弱い紐帯の強み』。都市社会学の最前線。",
    lead_snippet: "「話しかけたら嫌がられるだろう」という人々の思い込み（多元的無知）を打ち破る社会心理学実験。カフェの店員やすれ違う人との挨拶が、都市生活者の主観的幸福度を劇的に高めるメカニズム。",
    source_name: "Journal of Personality and Social Psychology / The Atlantic (Oct 6, 2026)",
    source_media_key: "the-conversation",
    source_url: "https://www.theatlantic.com/health/archive/2026/10/casual-stranger-connections/",
    path: "society/psychology-casual-encounters/index.html",
    image: "https://images.unsplash.com/photo-1477959858617-67f30bc75b82?w=1000&auto=format&fit=crop&q=80"
  },
  {
    slug: "clarkson-business-red-tape",
    category: "society",
    category_label: "SOCIETY & RURAL ECONOMY",
    date: "2026-10-05",
    title: "Jeremy Clarkson: Why Would Anyone Open a New Venture in Britain?",
    headline_ja: "ジェレミー・クラークソン氏寄稿：『いま英国で誰が新規事業など始めるのか？』",
    subhead: "規制緩和と地方経済の疲弊。反語表現（Rhetorical Question）の読解演習と経済英語。",
    lead_snippet: "人気テレビ司会者が地方農場レストラン経営で直面した過剰な規制と自治体官僚主義。起業意欲を削ぐ地方自治体のレッドテープ（お役所仕事）を痛烈に批判する論説文。",
    source_name: "The Sunday Times (Oct 5, 2026)",
    source_media_key: "ft",
    source_url: "https://www.thetimes.co.uk/article/jeremy-clarkson-business-red-tape",
    path: "society/clarkson-business-red-tape/index.html",
    image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1000&auto=format&fit=crop&q=80"
  },
  {
    slug: "inheritance-tax-reform-debate",
    category: "society",
    category_label: "SOCIETY & POLITICAL ECONOMY",
    date: "2026-10-02",
    title: "Badenoch Puts Inheritance Tax Reform at the Heart of Policy Agenda",
    headline_ja: "英国保守党党首候補ベイデノック氏、相続税改革を政策綱領の核心に提示",
    subhead: "相続税と世代間格差。税制倫理を論じる大学入試論述頻出のキーワード群と政治哲学。",
    lead_snippet: "富の世代間移転と機会の平等（equality of opportunity）をめぐる英国保守党の税制改革論争。親が築いた資産を子が受け継ぐ正当性と、再分配を重視する累進課税の思想的対立。",
    source_name: "The Times UK / Financial Times (Oct 2, 2026)",
    source_media_key: "the-times",
    source_url: "https://www.thetimes.co.uk/article/badenoch-inheritance-tax-reform",
    path: "society/inheritance-tax-reform-debate/index.html",
    image: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=1000&auto=format&fit=crop&q=80"
  },
  {
    slug: "raf-fairford-bomber-redeployment",
    category: "world",
    category_label: "WORLD & DIPLOMACY",
    date: "2026-10-01",
    title: "US Strategic Bombers Relocated From RAF Fairford Amid Regional Drone Alerts",
    headline_ja: "米空軍戦略爆撃機、中東ドローン警戒の高まりを受けフェアフォード英空軍基地から再配置",
    subhead: "国際法・安保条約上の兵力再配置（redeployment）と抑止力（deterrence）の軍事・外交英語構文。",
    lead_snippet: "党派的プロパガンダを排し、NATO集団防衛条約第5条および地位協定（SOFA）に基づく戦力再配備を客観的事実として報道。抑止力維持とエスカレーション防止の国際関係論。",
    source_name: "Reuters / AP News (Oct 1, 2026)",
    source_media_key: "reuters",
    source_url: "https://www.reuters.com/world/europe/us-bombers-fairford-redeployment",
    path: "world/raf-fairford-bomber-redeployment/index.html",
    image: "https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=1000&auto=format&fit=crop&q=80"
  },
  {
    slug: "critical-minerals-geopolitics",
    category: "world",
    category_label: "WORLD & RESOURCE DIPLOMACY",
    date: "2026-10-04",
    title: "The Geopolitics of Critical Minerals: Western Democracies Forge Supply Chain Pacts",
    headline_ja: "重要鉱物を巡る地政学：欧米諸国、サプライチェーン強靱化と同盟協定を締結",
    subhead: "脱炭素社会と経済安全保障を握るリチウム・希土類の囲い込み。資源外交と国際通商法の論理。",
    lead_snippet: "再生可能エネルギーへの移行に伴い需要が急増する重要鉱物。製錬能力の地理的集中がもたらす地政学的脆弱性を軽減するため、欧米先進国が締結した画期的な多国間パートナーシップの全貌。",
    source_name: "Financial Times / Reuters (Oct 4, 2026)",
    source_media_key: "ft",
    source_url: "https://www.ft.com/content/critical-minerals-geopolitics-alliance",
    path: "world/critical-minerals-geopolitics/index.html",
    image: "https://images.unsplash.com/photo-1578328819058-b69f3a3b0f6b?w=1000&auto=format&fit=crop&q=80"
  },
  {
    slug: "arctic-sea-route-unclos",
    category: "world",
    category_label: "WORLD & MARITIME DIPLOMACY",
    date: "2026-10-03",
    title: "Melting Ice, Contested Waters: The Arctic Sea Route and UNCLOS Sovereignty Clashes",
    headline_ja: "融解する氷と角逐する領海：北極海航路の開放と国連海洋法条約（UNCLOS）を巡る主権衝突",
    subhead: "地球温暖化が生んだ最短航路の商業化と航行の自由原則。海洋法秩序と安全保障の相克。",
    lead_snippet: "極地の海氷融解により商業化が進む北極海航路。輸送時間大幅短縮の利便性と、沿岸国の環境管轄権・通行料徴収、国際慣習法に基づく航行の自由が衝突する国際海洋法の最前線。",
    source_name: "The Times UK / Nature Climate Change (Oct 3, 2026)",
    source_media_key: "the-times",
    source_url: "https://www.thetimes.co.uk/article/arctic-sea-route-unclos-sovereignty",
    path: "world/arctic-sea-route-unclos/index.html",
    image: "https://images.unsplash.com/photo-1483181957632-8bda974cbc91?w=1000&auto=format&fit=crop&q=80"
  },
  {
    slug: "stoic-philosophy-digital-age",
    category: "culture",
    category_label: "CULTURE & CLASSICAL THOUGHT",
    date: "2026-10-02",
    title: "Ancient Antidotes to Algorithmic Anxiety: The Modern Renaissance of Stoic Philosophy",
    headline_ja: "アルゴリズム時代の不安に効く古代の処方箋：ストア派哲学の現代的復権",
    subhead: "エピクテトスとマルクス・アウレリウスが説いた「制御の二分法」。常時接続社会を生き抜く精神の強靭さ。",
    lead_snippet: "SNS通知と承認欲求のループに疲弊した現代人が見出す古代ストア哲学の知恵。自分の力で変えられる内面と変えられない外界を峻別する『制御の二分法』と認知的レジリエンスの深層。",
    source_name: "TIME Magazine / The Conversation (Oct 2, 2026)",
    source_media_key: "time",
    source_url: "https://time.com/stoicism-algorithmic-anxiety-modern-life",
    path: "culture/stoic-philosophy-digital-age/index.html",
    image: "https://images.unsplash.com/photo-1544717305-2782549b5136?w=1000&auto=format&fit=crop&q=80"
  },
  {
    slug: "smart-glasses-ai-privacy",
    category: "entertainment",
    category_label: "ENTERTAINMENT & GADGETS • ガジェット・情報倫理",
    date: "2026-10-09",
    title: "Augmented Reality, Ambient Surveillance: The Socio-Legal Dilemma of Generative AI Smart Glasses",
    headline_ja: "拡張現実と日常的監視の狭間：生成AIスマートグラスが突きつける法とプライバシーの現代的相克",
    subhead: "米MetaやRay-Banの最新AIグラス普及が引き起こす盗撮・顔認識不安。公共空間の匿名性と情報倫理を学術英語で徹底解剖。",
    lead_snippet: "日常の風景に溶け込む最新スマートグラスの急速な普及は、ハンズフリーの利便性をもたらす一方で、同意なき録画やリアルタイム顔認識によるプライバシー侵害の懸念をかつてない次元に押し上げている。技術の利便性と市民の匿名性保護を巡る法制度・エチケットの最前線を精読する。",
    source_name: "GetNews Japan (ガジェット通信 / Tech & Entertainment Special Analysis)",
    source_media_key: "getnews",
    source_url: "https://getnews.jp/archives/smart-glasses-ai-privacy",
    path: "entertainment/smart-glasses-ai-privacy/index.html",
    image: "https://images.unsplash.com/photo-1593508512255-86ab42a8e620?w=1000&auto=format&fit=crop&q=80"
  },
  {
    slug: "japan-semiconductor-revival-rapidus",
    category: "science",
    category_label: "SCIENCE & TECH • 産業技術・国際地政学",
    date: "2026-10-09",
    title: "Japan's Strategic Semiconductor Gamble: Rapidus and the Geopolitics of 2-Nanometer Chips",
    headline_ja: "日本の国家半導体再興戦略：ラピダス北海道工場と2ナノメートル極微細加工を巡る世界的技術覇権",
    subhead: "官民一体の巨額投資と日米欧の技術同盟。シリコン列島復活に向けたサプライチェーン再構築を経済安全保障英語で精読。",
    lead_snippet: "日本政府は2ナノメートル未満の最先端半導体を国内製造すべく数兆円規模の国家戦略に踏み切った。国策ベンチャー・ラピダスは地政学的サプライチェーン寸断への対抗軸となり得るのか。巨額の資本注入と極端紫外線（EUV）露光技術者の育成という高い障壁を検証する。",
    source_name: "Jiji Press (時事通信 / Japan's Independent News Agency)",
    source_media_key: "jiji",
    source_url: "https://www.jiji.com/jc/article?k=japan-semiconductor-rapidus",
    path: "science/japan-semiconductor-revival-rapidus/index.html",
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=1000&auto=format&fit=crop&q=80"
  },
  {
    slug: "digital-school-backpack-reform",
    category: "society",
    category_label: "SOCIETY & EDUCATION • 現代教育・身体健康",
    date: "2026-10-09",
    title: "The Heavy Burden of Pedagogy: Japanese Classrooms Address Digital Tablets and Backpack Strain",
    headline_ja: "教育現場の重すぎる負担：児童生徒のデジタル端末導入と伝統的ランドセルを巡る身体的・教育的相克",
    subhead: "1人1台端末の普及が生んだ「ランドセル症候群」。紙の教科書とクラウド学習の最適なバランスを社会科学英語で探究。",
    lead_snippet: "全国の学校で進むGIGAスクール構想の下、タブレット端末の配備が加速したものの、依然として紙の教科書を全量持ち運ぶ慣習により小学生の通学鞄が過重化する皮肉な現象が生じている。小児整形外科学の警告と、置き勉・人間工学リュック導入を模索する自治体の挑戦を追う。",
    source_name: "Yahoo! News Japan (Yahoo!ニュース / Education & Society Special Feature)",
    source_media_key: "yahoo",
    source_url: "https://news.yahoo.co.jp/articles/digital-school-backpack-reform",
    path: "society/digital-school-backpack-reform/index.html",
    image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1000&auto=format&fit=crop&q=80"
  },
  {
    slug: "nihon-hidankyo-nobel-peace-prize",
    category: "world",
    category_label: "WORLD & PEACE • 国際平和・ノーベル賞",
    date: "2026-10-09",
    title: "The Moral Imperative of the Nuclear Taboo: Nihon Hidankyo Wins the 2024 Nobel Peace Prize",
    headline_ja: "日本被団協にノーベル平和賞：「核兵器不使用の規範（タブー）」を守り続けた被爆者の生きた証言",
    subhead: "広島・長崎の被爆者組織が歩んだ不屈の半世紀。ウクライナや中東情勢で核威嚇が高まる中、国際社会が再確認した人道主義を学術英語で精読。",
    lead_snippet: "ノルウェー・ノーベル委員会は、広島・長崎の被爆者による草の根団体「日本被団協」に2024年ノーベル平和賞を授与することを決定した。悲痛な個人の記憶をたゆまぬ世界規模の運動へと昇華させ、核兵器不使用の国際規範（核のタブー）を定着させてきた被爆者の証言が持つ道義的権威を検証する。",
    source_name: "Jiji Press & Reuters (時事通信・オスロ共同特派 / Nobel Committee Announcement)",
    source_media_key: "jiji",
    source_url: "https://www.jiji.com/jc/article?k=nihon-hidankyo-nobel-peace-prize",
    path: "world/nihon-hidankyo-nobel-peace-prize/index.html",
    image: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=1000&auto=format&fit=crop&q=80"
  },
  {
    slug: "regulatory-t-cells-nobel-breakthrough",
    category: "science",
    category_label: "SCIENCE & MEDICINE • 免疫学・ノーベル賞級研究",
    date: "2026-10-09",
    title: "Mastering the Cellular Brake: How Shimon Sakaguchi's Regulatory T Cells Revolutionized Immunology",
    headline_ja: "免疫の暴走を止める「ブレーキ役」の発見：坂口志文氏の制御性T細胞（Treg）研究が拓くがん治療の新時代",
    subhead: "自己免疫疾患の謎を解き明かし、がん免疫療法の礎となった世界的発見。ノーベル賞有力候補として注目を集める日本人免疫学者を学術英語で精読。",
    lead_snippet: "細胞免疫学における画期的な貢献として、日本人科学者の坂口志文教授は「制御性T細胞（Treg）」が不可欠な免疫ブレーキとして機能することを発見した。病原体のみを無力化し自己組織を攻撃しない生命の精緻なバランスと、がん治療への応用を精読する。",
    source_name: "Jiji Press & Nature Medicine (時事通信学術特報 / Osaka University IFReC)",
    source_media_key: "jiji",
    source_url: "https://www.jiji.com/jc/article?k=regulatory-t-cells-sakaguchi",
    path: "science/regulatory-t-cells-nobel-breakthrough/index.html",
    image: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=1000&auto=format&fit=crop&q=80"
  },
  {
    slug: "soai-reaction-nobel-chemistry",
    category: "science",
    category_label: "SCIENCE & CHEMISTRY • 2026年ノーベル化学賞",
    date: "2026-10-09",
    title: "Unlocking the Mystery of Homochirality: Kenso Soai Awarded the 2026 Nobel Prize in Chemistry",
    headline_ja: "生命の鏡像異性体（ホモキラリティー）の起源を解明：硤合憲三・東京理科大名誉教授に2026年ノーベル化学賞",
    subhead: "ごくわずかな分子の偏りが自らを爆発的に増幅する「硤合反応（不斉自己触媒反応）」の世界初発見。医薬品化学と宇宙生命科学を塗り替えた世界的金字塔を最高峰の学術英語で徹底解剖。",
    lead_snippet: "スウェーデン王立科学アカデミーは、2026年のノーベル化学賞を東京理科大学名誉教授の硤合憲三博士らに授与することを決定した。生命の分子がなぜ一方の鏡像異性体のみを選んだのかという「ホモキラリティーの起源」に世界で初めて化学的実証を与えた世界的業績を最高峰の英語で精読する。",
    source_name: "Jiji Press & Nature Chemistry (時事通信・ストックホルム特報 / Nobel Prize Committee Announcement)",
    source_media_key: "jiji",
    source_url: "https://www.jiji.com/jc/article?k=soai-reaction-nobel-chemistry-2026",
    path: "science/soai-reaction-nobel-chemistry/index.html",
    image: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=1000&auto=format&fit=crop&q=80"
  },
  {
    slug: "esports-highschool-education",
    category: "entertainment",
    category_label: "ENTERTAINMENT & EDUCATION",
    date: "2026-10-09",
    title: "From Gaming to Graduation: High School Esports Programs Boost Teamwork and Digital Literacy",
    headline_ja: "放課後ゲームから教育の最前線へ：高校の「eスポーツ部」が育むチームワークとデジタルリテラシー",
    subhead: "単なる娯楽から学校教育の新たな柱へ。全国高校eスポーツ選手権の広がりと戦略的思考力を英語で探る。",
    lead_snippet: "かつて従来の教育者たちから気晴らしに過ぎないと退けられていた競技型ゲームが、いまや高校の公式な部活動として制度化。戦術的コミュニケーションや回復力（レジリエンス）を培う教育的効果を精読する。",
    source_name: "GetNews Japan & Yahoo! News",
    source_media_key: "getnews",
    source_url: "https://getnews.jp/archives/esports-highschool-education",
    path: "entertainment/esports-highschool-education/index.html",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1000&auto=format&fit=crop&q=80"
  },
  {
    slug: "global-plastics-treaty-negotiations",
    category: "world",
    category_label: "WORLD & ENVIRONMENT",
    date: "2026-10-09",
    title: "A Binding Mandate for the Oceans: UN Delegates Convene to Finalize Global Plastics Treaty",
    headline_ja: "地球規模の海洋プラスチック条約最終交渉：法的拘束力を持つ国際協定の締結へ",
    subhead: "海洋汚染とマイクロプラスチックの根絶を目指す国連交渉。産油国と環境保護国の利害対立を国際法・環境外交の英語で読み解く。",
    lead_snippet: "170カ国以上の外交官がプラスチック汚染抑制に向けた法的拘束力のある世界条約案の策定で激論。一次ポリマーの生産上限設定を求める野心国とリサイクル重視国の攻防を検証する。",
    source_name: "Jiji Press & UN News",
    source_media_key: "jiji",
    source_url: "https://www.jiji.com/jc/article?k=global-plastics-treaty-un",
    path: "world/global-plastics-treaty-negotiations/index.html",
    image: "https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?w=1000&auto=format&fit=crop&q=80"
  },
  {
    slug: "cashless-society-local-bus-crisis",
    category: "society",
    category_label: "SOCIETY & TRANSPORT",
    date: "2026-10-09",
    title: "The Friction of Going Cashless: Rural Transit Systems Struggle with Fare Modernization",
    headline_ja: "完全キャッシュレス化の波と地方の戸惑い：路線バスの運賃改編と高齢社会のデジタル格差",
    subhead: "小銭の両替廃止や完全キャッシュレス決済の導入が進む一方、高齢者や通学児童の取り残しが課題に。交通権とデジタル化の摩擦を検証。",
    lead_snippet: "深刻な運転手不足とコスト高に直面する地方バス事業者が完全キャッシュレス運賃へと移行。乗車手続きの迅速化と、スマホを持たない高齢者への配慮の調和を社会政策論として読み解く。",
    source_name: "Yahoo! News Japan & Jiji Press",
    source_media_key: "yahoo",
    source_url: "https://news.yahoo.co.jp/articles/cashless-bus-transit-crisis",
    path: "society/cashless-society-local-bus-crisis/index.html",
    image: "https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=1000&auto=format&fit=crop&q=80"
  },
  {
    slug: "perovskite-solar-cells-commercialization",
    category: "science",
    category_label: "SCIENCE & CLEAN TECH",
    date: "2026-10-09",
    title: "Bending the Light: Japan Accelerates Commercial Rollout of Perovskite Solar Cells",
    headline_ja: "曲がる太陽電池「ペロブスカイト」の社会実装：日本発の次世代クリーンエネルギー革命",
    subhead: "ビル壁面や曲面にも設置可能なペロブスカイト太陽電池。主原料ヨウ素の世界的産出国である日本が世界標準を狙う技術開発を精読。",
    lead_snippet: "カーボンニュートラル達成に向け、柔軟で折り曲げ可能なペロブスカイト太陽電池の実用化が進展。ビルの曲面壁面や車体外装に直接貼れる次世代技術と日本のヨウ素サプライチェーンの強みを分析する。",
    source_name: "Jiji Press & Nikkei Science",
    source_media_key: "jiji",
    source_url: "https://www.jiji.com/jc/article?k=perovskite-solar-cells-japan",
    path: "science/perovskite-solar-cells-commercialization/index.html",
    image: "https://images.unsplash.com/photo-1509391365360-2e959784a276?w=1000&auto=format&fit=crop&q=80"
  },
  {
    slug: "space-debris-corporate-liability",
    category: "law",
    category_label: "LAW & AEROSPACE",
    date: "2026-10-09",
    title: "Orbital Gridlock: Legal Jurisdictions Clash Over Corporate Liability for Space Debris",
    headline_ja: "宇宙ゴミ（スペースデブリ）の企業賠償責任：軌道混雑が生む宇宙法の新フロンティア",
    subhead: "メガコンステレーション衛星の急増で衝突リスクが激増。宇宙条約（Outer Space Treaty）の限界と民間企業の責任法理を考察。",
    lead_snippet: "民間企業による数万基の衛星打ち上げに伴い、軌道上の宇宙ゴミ規制に関する1967年宇宙条約の不備が浮き彫りに。衝突連鎖（ケスラー・シンドローム）を防ぐ不法行為責任法理を法学英語で精読する。",
    source_name: "Financial Times & Jiji Press",
    source_media_key: "ft",
    source_url: "https://www.ft.com/content/space-debris-liability-law",
    path: "law/space-debris-corporate-liability/index.html",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1000&auto=format&fit=crop&q=80"
  },
  {
    slug: "handwriting-cognitive-benefits",
    category: "culture",
    category_label: "CULTURE & NEUROSCIENCE",
    date: "2026-10-09",
    title: "The Pen Still Rules the Brain: Neuroscientists Reaffirm Cognitive Superiority of Handwriting",
    headline_ja: "手書きが脳を覚醒させる：神経科学が実証したタイピングを超える記憶定着と創造性",
    subhead: "タブレット学習が広がる今こそ見直される「手書き」の価値。脳波測定実験から明らかになった脳内ネットワークの活性化を精読。",
    lead_snippet: "タッチ画面が教育現場を席巻する今、文字を手書きすることが豊かな神経同期を生み出すという科学的知見。要約と言い換えを伴う手書きの触覚的価値を認知心理学で解明する。",
    source_name: "TIME Magazine & Frontiers in Psychology",
    source_media_key: "time",
    source_url: "https://time.com/handwriting-brain-connectivity-study",
    path: "culture/handwriting-cognitive-benefits/index.html",
    image: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=1000&auto=format&fit=crop&q=80"
  },
  {
    slug: "remote-work-suburban-revitalization",
    category: "society",
    category_label: "SOCIETY & URBAN PLANNING",
    date: "2026-10-09",
    title: "Beyond the Megacity: How Hybrid Work Is Quietly Rebuilding Japan's Regional Towns",
    headline_ja: "首都圏一極集中からの脱却：ハイブリッドワークが静かに後押しする地方移住と空き家再生",
    subhead: "完全出社回帰でも完全フルリモートでもない「週2日通勤圏」。地方都市に移住した子育て世代が拓く地域活性化の新たな潮流。",
    lead_snippet: "週2〜3日の出社で済む柔軟なハイブリッドワークが、東京2時間圏内の海沿い・山あいの自治体に子育て世代の移住をもたらし、空き家再生と地域経済の活性化を促す好循環を分析する。",
    source_name: "Yahoo! News Japan",
    source_media_key: "yahoo",
    source_url: "https://news.yahoo.co.jp/articles/hybrid-work-rural-revitalization",
    path: "society/remote-work-suburban-revitalization/index.html",
    image: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1000&auto=format&fit=crop&q=80"
  },
  {
    slug: "ai-music-copyright-royalties",
    category: "entertainment",
    category_label: "ENTERTAINMENT & IP LAW",
    date: "2026-10-09",
    title: "Harmony or Theft? The Global Music Industry Demands Fair Royalties from Generative AI",
    headline_ja: "調和か盗用か：生成AI楽曲の急増と世界音楽業界が求める著作権対価の新ルール",
    subhead: "有名アーティストの声を再現したAI楽曲がストリーミングで数百万回再生。クリエイターの権利と技術革新のせめぎ合いを読み解く。",
    lead_snippet: "有名歌手の音色や歌唱リズムを模倣したAI楽曲の氾濫に対し、音楽レコード産業界が法的手続きに乗り出す。著作権保護とフェアユースの境界、創造性の経済的基盤を精読する。",
    source_name: "GetNews Japan & Billboard",
    source_media_key: "getnews",
    source_url: "https://getnews.jp/archives/ai-music-copyright-royalties",
    path: "entertainment/ai-music-copyright-royalties/index.html",
    image: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1000&auto=format&fit=crop&q=80"
  },
  {
    slug: "ai-energy-nuclear-data-centers",
    category: "world",
    category_label: "WORLD & ENERGY",
    date: "2026-10-09",
    title: "Powering the AI Surge: Tech Giants Turn to Nuclear Energy to Feed Insatiable Data Centers",
    headline_ja: "AI時代の電力危機：巨大テック企業がデータセンターの脱炭素電源に「小型原子力」を選ぶ理由",
    subhead: "生成AIの計算処理に必要な電力消費が激増。24時間安定したゼロエミッション電力を求め、原子力発電の再評価が進む地政学的背景。",
    lead_snippet: "生成AIの天文学的な電力消費を受け、米ハイテク巨頭各社が原子力事業者との直接調達契約を加速。再エネの間欠性を補う24時間ベースロード電源としての原発再評価と地政学的意味を検証する。",
    source_name: "Reuters & Jiji Press",
    source_media_key: "reuters",
    source_url: "https://www.jiji.com/jc/article?k=ai-nuclear-data-centers",
    path: "world/ai-energy-nuclear-data-centers/index.html",
    image: "https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=1000&auto=format&fit=crop&q=80"
  }
];

const EDITIONS = {
  "2026-10-09": {
    dateStr: "Friday October 9 2026",
    editionLabel: "2026年10月9日 (金) 号 【本日最新版】",
    tagline: "特集：東京理科大・硤合憲三名誉教授に2026年ノーベル化学賞・坂口志文教授の制御性T細胞・AIスマートグラス倫理",
    topLeadSlug: "soai-reaction-nobel-chemistry",
    subLeadSlugs: ["regulatory-t-cells-nobel-breakthrough", "smart-glasses-ai-privacy"],
    leftDispatches: ["japan-semiconductor-revival-rapidus", "digital-school-backpack-reform", "nihon-hidankyo-nobel-peace-prize"],
    rightDigestSlugs: ["critical-minerals-geopolitics", "colorectal-cancer-under-50s", "headphones-in-public", "air-defence-shield"]
  },
  "2026-10-08": {
    dateStr: "Thursday October 8 2026",
    editionLabel: "2026年10月8日 (木) 号 【バックナンバー】",
    tagline: "特集：脱炭素の生命線・重要鉱物同盟とストア派哲学の認知的レジリエンス",
    topLeadSlug: "critical-minerals-geopolitics",
    subLeadSlugs: ["stoic-philosophy-digital-age", "mediterranean-marine-heatwaves"],
    leftDispatches: ["psychology-casual-encounters", "air-defence-shield", "colorectal-cancer-under-50s"],
    rightDigestSlugs: ["headphones-in-public", "clarkson-business-red-tape", "inheritance-tax-reform-debate", "ai-pediatric-diagnosis-consent"]
  },
  "2026-10-07": {
    dateStr: "Wednesday October 7 2026",
    editionLabel: "2026年10月7日 (水) 号 【バックナンバー】",
    tagline: "特集：都市の孤独を癒やす挨拶の魔法と北極海航路・国際海洋法争奪戦",
    topLeadSlug: "psychology-casual-encounters",
    subLeadSlugs: ["arctic-sea-route-unclos", "generative-ai-paleontology"],
    leftDispatches: ["critical-minerals-geopolitics", "royal-security-judicial-review", "raf-fairford-bomber-redeployment"],
    rightDigestSlugs: ["headphones-in-public", "stoic-philosophy-digital-age", "colorectal-cancer-under-50s", "air-defence-shield"]
  },
  "2026-10-06": {
    dateStr: "Tuesday October 6 2026",
    editionLabel: "2026年10月6日 (火) 号 【バックナンバー】",
    tagline: "特集：公共空間のイヤホン論争と都市の孤独・偶発的出会いの心理学",
    topLeadSlug: "headphones-in-public",
    subLeadSlugs: ["jeffrey-archer-obituary", "royal-security-judicial-review"],
    leftDispatches: ["air-defence-shield", "colorectal-cancer-under-50s", "raf-fairford-bomber-redeployment"],
    rightDigestSlugs: ["clarkson-business-red-tape", "inheritance-tax-reform-debate", "ai-pediatric-diagnosis-consent", "mediterranean-marine-heatwaves"]
  },
  "2026-10-05": {
    dateStr: "Monday October 5 2026",
    editionLabel: "2026年10月5日 (月) 号 【バックナンバー】",
    tagline: "特集：英国100億ポンド防衛シールド審議と司法審査・王室警護裁量",
    topLeadSlug: "air-defence-shield",
    subLeadSlugs: ["royal-security-judicial-review", "clarkson-business-red-tape"],
    leftDispatches: ["headphones-in-public", "inheritance-tax-reform-debate", "mediterranean-marine-heatwaves"],
    rightDigestSlugs: ["jeffrey-archer-obituary", "ai-pediatric-diagnosis-consent", "colorectal-cancer-under-50s", "raf-fairford-bomber-redeployment"]
  },
  "2026-10-04": {
    dateStr: "Sunday October 4 2026",
    editionLabel: "2026年10月4日 (日) 号 【バックナンバー】",
    tagline: "特集：50歳未満の大腸がん世界的急増と地中海深海熱波の生体ストレス",
    topLeadSlug: "colorectal-cancer-under-50s",
    subLeadSlugs: ["mediterranean-marine-heatwaves", "generative-ai-paleontology"],
    leftDispatches: ["ai-pediatric-diagnosis-consent", "psychology-casual-encounters", "inheritance-tax-reform-debate"],
    rightDigestSlugs: ["headphones-in-public", "air-defence-shield", "clarkson-business-red-tape", "jeffrey-archer-obituary"]
  },
  "2026-10-03": {
    dateStr: "Saturday October 3 2026",
    editionLabel: "2026年10月3日 (土) 号 【バックナンバー】",
    tagline: "特集：小児AI診断の親同意権と古生物学における生成ニューラルネットワーク",
    topLeadSlug: "ai-pediatric-diagnosis-consent",
    subLeadSlugs: ["generative-ai-paleontology", "royal-security-judicial-review"],
    leftDispatches: ["clarkson-business-red-tape", "colorectal-cancer-under-50s", "jeffrey-archer-obituary"],
    rightDigestSlugs: ["headphones-in-public", "mediterranean-marine-heatwaves", "psychology-casual-encounters", "inheritance-tax-reform-debate"]
  },
  "2026-10-02": {
    dateStr: "Friday October 2 2026",
    editionLabel: "2026年10月2日 (金) 号 【バックナンバー】",
    tagline: "特集：相続税改革と世代間格差の政治哲学・クラークソン英起業規制論",
    topLeadSlug: "inheritance-tax-reform-debate",
    subLeadSlugs: ["clarkson-business-red-tape", "psychology-casual-encounters"],
    leftDispatches: ["raf-fairford-bomber-redeployment", "royal-security-judicial-review", "generative-ai-paleontology"],
    rightDigestSlugs: ["air-defence-shield", "colorectal-cancer-under-50s", "headphones-in-public", "ai-pediatric-diagnosis-consent"]
  },
  "2026-10-01": {
    dateStr: "Thursday October 1 2026",
    editionLabel: "2026年10月1日 (木) 号 【創刊バックナンバー】",
    tagline: "特集：フェアフォード米戦略爆撃機再配置とジェフリー・アーチャー氏追悼",
    topLeadSlug: "raf-fairford-bomber-redeployment",
    subLeadSlugs: ["jeffrey-archer-obituary", "generative-ai-paleontology"],
    leftDispatches: ["air-defence-shield", "inheritance-tax-reform-debate", "mediterranean-marine-heatwaves"],
    rightDigestSlugs: ["clarkson-business-red-tape", "psychology-casual-encounters", "royal-security-judicial-review", "headphones-in-public"]
  }
};
