// THE ACADEMIC TIMES - Master Portal Data & Media Literacy Knowledge Base
// Contains all 57 articles, daily editions, and high-school media literacy references.

const MEDIA_RESOURCES = [
  {
    "key": "time",
    "name": "TIME Magazine (米国・オピニオン週刊誌)",
    "country": "USA",
    "founded": "1923年",
    "stance": "教養・分析・中道リベラル",
    "examSignificance": "早慶・上智・東大など難関大入試長文で過去30年間最頻出。感情論を排し、認知心理学や統計データに基づいた論証型エッセイの最高峰。",
    "whyHighSchoolersMustKnow": "ニュースに興味がない高校生でも、TIME誌の『日常の当たり前を疑うエッセイ』を読むだけで、自由英作文や小論文で問われる論理構成（主張→具体例→反論の考慮）が自然と身につきます。",
    "sampleTopics": "デジタル社会の孤独、退屈と創造性、労働観の変容、宇宙探査の意義",
    "badge": "頻出度: Sランク（文理共通）"
  },
  {
    "key": "the-times",
    "name": "The Times (英国・本格高級日刊紙)",
    "country": "UK",
    "founded": "1785年",
    "stance": "伝統的保守・格調高い言論",
    "examSignificance": "世界標準フォント『Times New Roman』の発祥元。英国議会政治、法制度、司法判断の最高権威。東大・京大・一橋の要約・下線部和訳の定番出典。",
    "whyHighSchoolersMustKnow": "簡潔で引き締まった格調高い文体（The Times Style）は、文法的に厳密な複文（倒置・同格・分詞構文）の宝庫。正確な英文解釈力を鍛えるのに最適です。",
    "sampleTopics": "国家安全保障、司法審査、王室・憲法制度、大英帝国の歴史的検証",
    "badge": "頻出度: Sランク（難関国公立2次）"
  },
  {
    "key": "the-guardian",
    "name": "The Guardian (英国・国際的リベラル高級紙)",
    "country": "UK",
    "founded": "1821年",
    "stance": "中道リベラル・環境・調査報道",
    "examSignificance": "世界で最も読まれるオンライン高級紙の一つ。環境問題、人権、AI倫理、社会的不平等など『現代の重要課題』を最も深く追究するメディア。",
    "whyHighSchoolersMustKnow": "全記事が完全無料公開されているため、高校生の独習に最適。現代社会・倫理の教科書に載っているようなテーマの最前線を生きた英語で学べます。",
    "sampleTopics": "気候変動、AI診断と親の同意、貧困と教育格差、監視資本主義批判",
    "badge": "頻出度: Sランク（自由英作文・小論文直結）"
  },
  {
    "key": "nature",
    "name": "Nature & Nature Medicine (国際総合科学学術誌)",
    "country": "UK / Global",
    "founded": "1869年",
    "stance": "厳格な査読制・自然科学最高峰",
    "examSignificance": "医学部・東工大・京大理系などの超難関長文で毎年必ず出題。最新の疫学、がん研究、気候変動データを客観的に論じる専門英語。",
    "whyHighSchoolersMustKnow": "科学論文特有の論理展開（Background → Hypothesis → Method → Result → Discussion）を高校生のうちに掴むことで、共通テストの図表問題も一瞬で解けるようになります。",
    "sampleTopics": "若年性がん急増の疫学、マイクロプラスチック、腸内細菌叢、ゲノム編集",
    "badge": "頻出度: 特Aランク（医学部・難関理系）"
  },
  {
    "key": "science-mag",
    "name": "Science (全米科学振興協会・世界的学術誌)",
    "country": "USA",
    "founded": "1880年（トーマス・エジソンが創刊支援）",
    "stance": "先端科学総合・文理融合",
    "examSignificance": "Natureと双璧をなす世界最高峰の学術誌。計算生物学、生成AIを用いた進化の解明、量子力学など文理融合の学際的テーマに強い。",
    "whyHighSchoolersMustKnow": "AIを使って絶滅動物の歩き方を再現するなど、知的好奇心を刺激する最先端の研究を英語で知ることで、大学で何を学びたいかの探究学習に繋がります。",
    "sampleTopics": "AI古生物学、計算生物学、超電導、気候モデリング",
    "badge": "頻出度: 特Aランク（理系・情報系・総合型）"
  },
  {
    "key": "ft",
    "name": "Financial Times (英国・国際経済政治高級紙)",
    "country": "UK / Global",
    "founded": "1888年（サーモンピンクの紙面が象徴）",
    "stance": "自由市場・グローバル資本主義・政策精査",
    "examSignificance": "慶應経済・法、一橋大、東大文系で圧倒的信頼を誇る出典。防衛予算の使途、国際サプライチェーン、金融政策を冷静に数字で検証。",
    "whyHighSchoolersMustKnow": "感情論になりがちな政治・社会問題を『財政・コスト・費用対効果』の視点で冷徹に捉える思考法が養われ、慶應小論文の合格レベルに直結します。",
    "sampleTopics": "防衛調達の透明性、重要鉱物の囲い込み、エネルギー転換のコスト、中央銀行デジタル通貨",
    "badge": "頻出度: Sランク（難関社会科学系）"
  },
  {
    "key": "reuters",
    "name": "Reuters (世界最大級の国際総合通信社)",
    "country": "UK / Global",
    "founded": "1851年",
    "stance": "完全中立・客観報道・速報性",
    "examSignificance": "記者の主観や形容詞を極力排除し、事実（Fact）のみを正確に伝える最高峰の通信社英語。共通テストや国公立2次の事実把握問題の基礎。",
    "whyHighSchoolersMustKnow": "世界中のニュースの『大元の一次情報』がどう書かれているかを知ることで、ネット上のフェイクニュースや偏向報道に惑わされないメディアリテラシーが身につきます。",
    "sampleTopics": "米軍爆撃機再配置、地中海深海熱波、国連気候サミット、サプライチェーン速報",
    "badge": "客観性: 世界基準（ファクトチェック必須）"
  },
  {
    "key": "jiji",
    "name": "Jiji Press (時事通信社・国内総合通信社)",
    "country": "Japan",
    "founded": "1945年",
    "stance": "国政・行政・金融・経済安全保障のファクト重視",
    "examSignificance": "日本政府・経産省の政策決定、ラピダス半導体プロジェクト、最高裁判所判例など、日本の最重要国策を正確な一次情報として発信。",
    "whyHighSchoolersMustKnow": "国内で起きている重要国策や法改正を世界水準の英語でどう発信・表現するかを学ぶことで、日本の課題をグローバルな視点から客観的に論じる力が身につきます。",
    "sampleTopics": "ラピダス2nm半導体支援、楽譜ネット無断複製最高裁判決、プラ条約、日米地位協定",
    "badge": "信頼性: 国内一次報道の最高峰"
  },
  {
    "key": "yahoo",
    "name": "Yahoo! News Japan (国内最大級ニュースポータル・特集報道)",
    "country": "Japan",
    "founded": "1996年",
    "stance": "生活者目線・教育・社会課題・徹底深層取材",
    "examSignificance": "ランドセルの過重負担問題、地方路線バスの完全キャッシュレス化と高齢者移動権など、市民生活の最前線で起きているリアルな構造矛盾を掘り下げる特集記事群。",
    "whyHighSchoolersMustKnow": "自分たちの学校生活や身近な地域の困りごとが、そのまま大学入試の社会問題（公共・現代社会）の論述テーマになります。日常の違和感を英語で言語化する最高の素材です。",
    "sampleTopics": "小学生ランドセル10kg問題とデジタル教科書、地方路線バスの維持とキャッシュレス化、郊外サテライト移住",
    "badge": "身近度: Aランク（現代社会・身近な課題）"
  },
  {
    "key": "getnews",
    "name": "GetNews Japan (ガジェット通信・先端カルチャー)",
    "country": "Japan",
    "founded": "2008年",
    "stance": "デジタルカルチャー・先端ガジェット・ゲーム・ネット世論",
    "examSignificance": "AIスマートグラスによる常時録画と公衆プライバシー、高校eスポーツ部活の教育的妥当性など、デジタルネイティブ世代が直面する先端テクノロジーと倫理のフロンティアを速報。",
    "whyHighSchoolersMustKnow": "最新のスマートデバイスやゲーム、SNSカルチャーをただ消費するだけでなく、『テクノロジーの進化が社会のルールや人間の尊厳をどう変えるか』を批判的に考える視点が得られます。",
    "sampleTopics": "AIスマートグラスのプライバシー、高校eスポーツ部活動の教育的価値、生成AI音楽と著作権",
    "badge": "先端性: Sランク（情報社会・テクノロジー倫理）"
  }
];

const ARTICLES = [
  {
    "slug": "headphones-in-public",
    "category": "culture",
    "category_label": "COGNITIVE PSYCHOLOGY & CULTURE • 認知心理学",
    "date": "2026-10-06",
    "title": "The Case Against Wearing Headphones in Public: Reclaiming the Power of Reverie",
    "headline_ja": "公共空間でイヤホンを外す効用：失われた「物思い（白昼夢）」を取り戻す",
    "subhead": "米週刊誌TIME掲載のエッセイ。常時接続と孤独、創造性を育む退屈の価値を認知心理学で徹底解説。",
    "lead_snippet": "米週刊誌TIME掲載のエッセイ。常時接続と孤独、創造性を育む退屈の価値を認知心理学で徹底解説。",
    "source_name": "TIME Magazine (Oct 5, 2026 / Meehika Barua)",
    "source_media_key": "time",
    "source_url": "https://time.com/article/2026/10/05/the-case-against-wearing-headphones-in-public/",
    "path": "culture/headphones-in-public/index.html",
    "image": "https://static.time.com/v3/assets/bltea6093859af6183b/blt96d6f358ea9d50b0/6abfba6215869b08e9e95a32/headphones.jpg?branch=production&width=1200&quality=80&auto=webp"
  },
  {
    "slug": "air-defence-shield",
    "category": "law",
    "category_label": "LAW & NATIONAL SECURITY • 入試長文頻出テーマ",
    "date": "2026-10-05",
    "title": "British Parliament Debates £10bn Integrated Air Defence Shield",
    "headline_ja": "英国議会、100億ポンド規模の統合防空シールド計画を審議",
    "subhead": "急速に進化する無人機技術と欧州安保の再編。議会統制と防衛調達の透明性を法学英語で精読。",
    "lead_snippet": "急速に進化する無人機技術と欧州安保の再編。議会統制と防衛調達の透明性を法学英語で精読。",
    "source_name": "The Times / Financial Times (2026年10月5日)",
    "source_media_key": "time",
    "source_url": "https://www.thetimes.com/defence/uk-air-shield-debate-2026",
    "path": "law/air-defence-shield/index.html",
    "image": "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "colorectal-cancer-under-50s",
    "category": "science",
    "category_label": "SCIENCE & MEDICINE • 入試長文頻出テーマ",
    "date": "2026-10-04",
    "title": "The Unsolved Surge: Colorectal Cancer Rates Among Under-50s",
    "headline_ja": "50歳未満の大腸がん急増：腸内細菌と超加工食品を巡る最新医学研究",
    "subhead": "若年層で急増するがん罹患率の謎。科学誌Natureが警告する現代の食環境、マイクロプラスチックと生体変容。",
    "lead_snippet": "若年層で急増するがん罹患率の謎。科学誌Natureが警告する現代の食環境、マイクロプラスチックと生体変容。",
    "source_name": "Nature Medicine / BBC Health (2026年10月4日)",
    "source_media_key": "nature",
    "source_url": "https://www.nature.com/articles/s41591-026-cancer-under50",
    "path": "science/colorectal-cancer-under-50s/index.html",
    "image": "https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "raf-fairford-bomber-redeployment",
    "category": "world",
    "category_label": "WORLD & SECURITY • 入試長文頻出テーマ",
    "date": "2026-10-01",
    "title": "Strategic Realignment: US Bombers Relocated From RAF Fairford Amid Drone Alerts",
    "headline_ja": "米戦略爆撃機、ドローン警戒を受け英フェアフォード基地から再配備",
    "subhead": "政治的偏向を排し、国際法・安保条約上の兵力再配置（redeployment）と抑止理論（deterrence）を検証。",
    "lead_snippet": "政治的偏向を排し、国際法・安保条約上の兵力再配置（redeployment）と抑止理論（deterrence）を検証。",
    "source_name": "Reuters / AP News (2026年10月6日)",
    "source_media_key": "reuters",
    "source_url": "https://www.reuters.com/world/europe/us-bombers-fairford-redeployment-2026",
    "path": "world/raf-fairford-bomber-redeployment/index.html",
    "image": "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "psychology-casual-encounters",
    "category": "society",
    "category_label": "SOCIETY & PSYCHOLOGY • 入試長文頻出テーマ",
    "date": "2026-10-06",
    "title": "The Fragile Serendipity: Why Megacities Starve for Everyday Micro-Interactions",
    "headline_ja": "都市の脆きセレンディピティ：なぜ大都会は見知らぬ他者との微小な触れ合いに飢えているのか",
    "subhead": "大都市の孤独と社会心理学。TIME誌イヤホン問題の科学的根拠となったシカゴ大学Epley教授の通勤実験を深掘り精読。",
    "lead_snippet": "大都市の孤独と社会心理学。TIME誌イヤホン問題の科学的根拠となったシカゴ大学Epley教授の通勤実験を深掘り精読。",
    "source_name": "Journal of Environmental Psychology / BBC Future (2026年10月5日)",
    "source_media_key": "nature",
    "source_url": "https://www.sciencedirect.com/journal/journal-of-environmental-psychology/2026/micro-encounters",
    "path": "society/psychology-casual-encounters/index.html",
    "image": "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "jeffrey-archer-obituary",
    "category": "culture",
    "category_label": "CULTURE & OBITUARY • 入試長文頻出テーマ",
    "date": "2026-10-01",
    "title": "Jeffrey Archer: The Flamboyant Storyteller Who Conquered British Bestsellers Dies at 86",
    "headline_ja": "ジェフリー・アーチャー氏死去（86歳）：英ベストセラー界を制覇した波乱万丈のストーリーテラー",
    "subhead": "全世界3億部超の物語作家。政界追放、服役、そして不屈の文学的再起を評伝英語で読み解く。",
    "lead_snippet": "全世界3億部超の物語作家。政界追放、服役、そして不屈の文学的再起を評伝英語で読み解く。",
    "source_name": "The Guardian / The Times (2026年10月5日)",
    "source_media_key": "the-guardian",
    "source_url": "https://www.theguardian.com/books/2026/oct/05/jeffrey-archer-obituary",
    "path": "culture/jeffrey-archer-obituary/index.html",
    "image": "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "royal-security-judicial-review",
    "category": "law",
    "category_label": "LAW & CONSTITUTION • 入試長文頻出テーマ",
    "date": "2026-10-05",
    "title": "The Sovereign and the State: Judicial Review and Royal Security Funding",
    "headline_ja": "君主と国家：王室警護費の撤回と司法審査（Judicial Review）を巡る憲法論争",
    "subhead": "公金支出の限界と国家の安全保障義務。英国憲法慣習法における行政裁量の司法統制を精読。",
    "lead_snippet": "公金支出の限界と国家の安全保障義務。英国憲法慣習法における行政裁量の司法統制を精読。",
    "source_name": "The Daily Telegraph / BBC News (2026年10月5日)",
    "source_media_key": "the-times",
    "source_url": "https://www.telegraph.co.uk/royal-family/2026/security-judicial-review-ruling",
    "path": "law/royal-security-judicial-review/index.html",
    "image": "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "clarkson-business-red-tape",
    "category": "society",
    "category_label": "SOCIETY & ECONOMICS • 入試長文頻出テーマ",
    "date": "2026-10-05",
    "title": "Jeremy Clarkson on British Enterprise: The Crippling Weight of Rural Regulation",
    "headline_ja": "ジェレミー・クラークソン、英産業論を語る：地方起業を蝕む官僚主義と規制の重圧",
    "subhead": "人気農場経営から見えた英国経済の閉塞感。規制緩和、地方創生、反語表現（Rhetoric）を入試英語で精読。",
    "lead_snippet": "人気農場経営から見えた英国経済の閉塞感。規制緩和、地方創生、反語表現（Rhetoric）を入試英語で精読。",
    "source_name": "The Sunday Times (2026年10月4日)",
    "source_media_key": "time",
    "source_url": "https://www.thetimes.co.uk/comment/jeremy-clarkson-rural-business-red-tape",
    "path": "society/clarkson-business-red-tape/index.html",
    "image": "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "inheritance-tax-reform-debate",
    "category": "society",
    "category_label": "SOCIETY & FISCAL POLICY • 入試長文頻出テーマ",
    "date": "2026-10-02",
    "title": "Inheritance Tax at the Crossroads: Wealth Disparity and Intergenerational Equity",
    "headline_ja": "岐路に立つ相続税：富の格差、世代間公平、そして中産階級の資産承継を巡る論争",
    "subhead": "ピケティの資本論から紐解く税制倫理。保守党党首候補の政策演説が浮き彫りにした財政と道徳の葛藤。",
    "lead_snippet": "ピケティの資本論から紐解く税制倫理。保守党党首候補の政策演説が浮き彫りにした財政と道徳の葛藤。",
    "source_name": "Financial Times / The Times (2026年10月5日)",
    "source_media_key": "ft",
    "source_url": "https://www.ft.com/content/inheritance-tax-reform-uk-2026",
    "path": "society/inheritance-tax-reform-debate/index.html",
    "image": "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "ai-pediatric-diagnosis-consent",
    "category": "law",
    "category_label": "LAW & BIOETHICS • 入試長文頻出テーマ",
    "date": "2026-10-03",
    "title": "Algorithmic Diagnosis in Critical Care: High Court Evaluates Parental Consent",
    "headline_ja": "小児救急医療におけるAI診断：高等法院、親の同意権とアルゴリズムの説明責任を審理",
    "subhead": "医療AIが下した救命判断を親が拒否できるか。子どもの最善の利益（Best Interests）と生命倫理の最前線。",
    "lead_snippet": "医療AIが下した救命判断を親が拒否できるか。子どもの最善の利益（Best Interests）と生命倫理の最前線。",
    "source_name": "BMJ / The Guardian (2026年10月6日)",
    "source_media_key": "the-guardian",
    "source_url": "https://www.theguardian.com/technology/2026/oct/06/high-court-ai-pediatric-diagnosis-consent",
    "path": "law/ai-pediatric-diagnosis-consent/index.html",
    "image": "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "mediterranean-marine-heatwaves",
    "category": "science",
    "category_label": "SCIENCE & MARINE CLIMATE • 入試長文頻出テーマ",
    "date": "2026-10-04",
    "title": "Abyssal Warmth: Marine Heatwaves Threaten Mediterranean Cold-Water Corals",
    "headline_ja": "深海の熱波：地中海の深海サンゴ群を脅かす未知の水温上昇と生態系クライシス",
    "subhead": "海面だけでなく水深数百メートルの暗黒街にまで達する熱波。気候変動が海洋熱塩循環に及ぼす不可逆的変容。",
    "lead_snippet": "海面だけでなく水深数百メートルの暗黒街にまで達する熱波。気候変動が海洋熱塩循環に及ぼす不可逆的変容。",
    "source_name": "Nature Climate Change / Science (2026年10月4日)",
    "source_media_key": "nature",
    "source_url": "https://www.nature.com/articles/s41558-026-med-heatwave",
    "path": "science/mediterranean-marine-heatwaves/index.html",
    "image": "https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "generative-ai-paleontology",
    "category": "science",
    "category_label": "SCIENCE & ARTIFICIAL INTELLIGENCE • 入試長文頻出テーマ",
    "date": "2026-10-03",
    "title": "Resurrecting Extinct Biomechanics: Generative Deep Learning in Paleontology",
    "headline_ja": "絶滅生物の運動を蘇らせる：古生物学における生成ディープラーニングと生体力学の融合",
    "subhead": "不完全な化石骨格から恐竜の走行を再構築する最新AI技術。計算科学が切り拓く仮説検証の新たな地平。",
    "lead_snippet": "不完全な化石骨格から恐竜の走行を再構築する最新AI技術。計算科学が切り拓く仮説検証の新たな地平。",
    "source_name": "Nature Machine Intelligence (2026年10月5日)",
    "source_media_key": "nature",
    "source_url": "https://www.nature.com/articles/s42256-026-paleo-ai",
    "path": "science/generative-ai-paleontology/index.html",
    "image": "https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "critical-minerals-geopolitics",
    "category": "world",
    "category_label": "WORLD & RESOURCE DIPLOMACY • 入試頻出テーマ",
    "date": "2026-10-06",
    "title": "The Geopolitics of Critical Minerals: Western Democracies Forge Supply Chain Pacts",
    "headline_ja": "重要鉱物を巡る地政学：欧米諸国、サプライチェーン強靱化と同盟協定を締結",
    "subhead": "脱炭素社会と経済安全保障を握るリチウム・希土類の囲い込み。資源外交と国際通商法の論理。",
    "lead_snippet": "脱炭素社会と経済安全保障を握るリチウム・希土類の囲い込み。資源外交と国際通商法の論理。",
    "source_name": "Financial Times / Reuters (Oct 4, 2026)",
    "source_media_key": "ft",
    "source_url": "https://www.ft.com/content/critical-minerals-geopolitics-alliance",
    "path": "world/critical-minerals-geopolitics/index.html",
    "image": "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "arctic-sea-route-unclos",
    "category": "world",
    "category_label": "WORLD & MARITIME DIPLOMACY • 入試頻出テーマ",
    "date": "2026-10-03",
    "title": "Melting Ice, Contested Waters: The Arctic Sea Route and UNCLOS Sovereignty Clashes",
    "headline_ja": "融解する氷と角逐する領海：北極海航路の開放と国連海洋法条約（UNCLOS）を巡る主権衝突",
    "subhead": "地球温暖化が生んだ最短航路の商業化と航行の自由原則。海洋法秩序と安全保障の相克。",
    "lead_snippet": "地球温暖化が生んだ最短航路の商業化と航行の自由原則。海洋法秩序と安全保障の相克。",
    "source_name": "The Times UK / Nature Climate Change (Oct 3, 2026)",
    "source_media_key": "time",
    "source_url": "https://www.thetimes.co.uk/article/arctic-sea-route-unclos-sovereignty",
    "path": "world/arctic-sea-route-unclos/index.html",
    "image": "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "stoic-philosophy-digital-age",
    "category": "culture",
    "category_label": "CULTURE & CLASSICAL THOUGHT • 入試頻出テーマ",
    "date": "2026-10-02",
    "title": "Ancient Antidotes to Algorithmic Anxiety: The Modern Renaissance of Stoic Philosophy",
    "headline_ja": "アルゴリズム時代の不安に効く古代の処方箋：ストア派哲学の現代的復権",
    "subhead": "エピクテトスとマルクス・アウレリウスが説いた「制御の二分法」。常時接続社会を生き抜く精神の強靭さ。",
    "lead_snippet": "エピクテトスとマルクス・アウレリウスが説いた「制御の二分法」。常時接続社会を生き抜く精神の強靭さ。",
    "source_name": "TIME Magazine / The Conversation (Oct 2, 2026)",
    "source_media_key": "time",
    "source_url": "https://time.com/stoicism-algorithmic-anxiety-modern-life",
    "path": "culture/stoic-philosophy-digital-age/index.html",
    "image": "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "smart-glasses-ai-privacy",
    "category": "entertainment",
    "category_label": "ENTERTAINMENT & GADGETS • ガジェット・先端倫理",
    "date": "2026-10-09",
    "title": "Next-Generation AI Smart Glasses and the Blurring Frontier of Public Privacy",
    "headline_ja": "次世代AIスマートグラスの台頭と公的プライバシーの境界融解：ウェアラブルカメラが突きつける新たな倫理課題",
    "subhead": "日常の視界を拡張する超軽量ARグラスと常時稼働AI。利便性の裏で問われる盗撮リスクと公共空間のデータ主権を論述英語で精読。",
    "lead_snippet": "日常の視界を拡張する超軽量ARグラスと常時稼働AI。利便性の裏で問われる盗撮リスクと公共空間のデータ主権を論述英語で精読。",
    "source_name": "GetNews Japan (ガジェット通信 / Tech, Gadgets & Digital Culture)",
    "source_media_key": "getnews",
    "source_url": "https://getnews.jp/archives/smart-glasses-ai-privacy",
    "path": "entertainment/smart-glasses-ai-privacy/index.html",
    "image": "https://images.unsplash.com/photo-1593508512255-86ab42a8e620?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "japan-semiconductor-revival-rapidus",
    "category": "science",
    "category_label": "SCIENCE & TECH • 産業技術・国際地政学",
    "date": "2026-10-09",
    "title": "Japan's Strategic Semiconductor Gamble: Rapidus and the Geopolitics of 2-Nanometer Chips",
    "headline_ja": "日本の国家半導体再興戦略：ラピダス北海道工場と2ナノメートル極微細加工を巡る世界的技術覇権",
    "subhead": "官民一体の巨額投資と日米欧の技術同盟。シリコン列島復活に向けたサプライチェーン再構築を経済安全保障英語で精読。",
    "lead_snippet": "官民一体の巨額投資と日米欧の技術同盟。シリコン列島復活に向けたサプライチェーン再構築を経済安全保障英語で精読。",
    "source_name": "Jiji Press (時事通信 / Japan's Independent News Agency)",
    "source_media_key": "jiji",
    "source_url": "https://www.jiji.com/jc/article?k=japan-semiconductor-rapidus",
    "path": "science/japan-semiconductor-revival-rapidus/index.html",
    "image": "https://images.unsplash.com/photo-1518770660439-4636190af475?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "digital-school-backpack-reform",
    "category": "society",
    "category_label": "SOCIETY & EDUCATION • 現代教育・身体健康",
    "date": "2026-10-09",
    "title": "The Heavy Burden of Pedagogy: Japanese Classrooms Address Digital Tablets and Backpack Strain",
    "headline_ja": "教育現場の重すぎる負担：児童生徒のデジタル端末導入と伝統的ランドセルを巡る身体的・教育的相克",
    "subhead": "1人1台端末の普及が生んだ「ランドセル症候群」。紙の教科書とクラウド学習の最適なバランスを社会科学英語で探究。",
    "lead_snippet": "1人1台端末の普及が生んだ「ランドセル症候群」。紙の教科書とクラウド学習の最適なバランスを社会科学英語で探究。",
    "source_name": "Yahoo! News Japan (Yahoo!ニュース / Education & Society Special Feature)",
    "source_media_key": "yahoo",
    "source_url": "https://news.yahoo.co.jp/articles/digital-school-backpack-reform",
    "path": "society/digital-school-backpack-reform/index.html",
    "image": "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "regulatory-t-cells-nobel-breakthrough",
    "category": "science",
    "category_label": "SCIENCE & MEDICINE • 免疫学・世界的日本人研究",
    "date": "2026-10-10",
    "title": "Mastering the Cellular Brake: How Shimon Sakaguchi's Regulatory T Cells Revolutionized Immunology",
    "headline_ja": "免疫の暴走を止める「ブレーキ役」の発見：坂口志文氏の制御性T細胞（Treg）研究が拓くがん治療の新時代",
    "subhead": "自己免疫疾患の謎を解き明かし、がん免疫療法の礎となった世界的発見。ノーベル賞有力候補として注目を集める日本人免疫学者を学術英語で精読。",
    "lead_snippet": "自己免疫疾患の謎を解き明かし、がん免疫療法の礎となった世界的発見。ノーベル賞有力候補として注目を集める日本人免疫学者を学術英語で精読。",
    "source_name": "Jiji Press & Nature Medicine (時事通信学術特報 / Osaka University IFReC)",
    "source_media_key": "jiji",
    "source_url": "https://www.jiji.com/jc/article?k=regulatory-t-cells-sakaguchi",
    "path": "science/regulatory-t-cells-nobel-breakthrough/index.html",
    "image": "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "soai-reaction-nobel-chemistry",
    "category": "science",
    "category_label": "SCIENCE & CHEMISTRY • 2026年ノーベル化学賞",
    "date": "2026-10-10",
    "title": "Unlocking the Mystery of Homochirality: Kenso Soai Awarded the 2026 Nobel Prize in Chemistry",
    "headline_ja": "生命の鏡像異性体（ホモキラリティー）の起源を解明：硤合憲三・東京理科大名誉教授に2026年ノーベル化学賞",
    "subhead": "ごくわずかな分子の偏りが自らを爆発的に増幅する「硤合反応（不斉自己触媒反応）」の世界初発見。医薬品化学と宇宙生命科学を塗り替えた世界的金字塔を最高峰の学術英語で徹底解剖。",
    "lead_snippet": "ごくわずかな分子の偏りが自らを爆発的に増幅する「硤合反応（不斉自己触媒反応）」の世界初発見。医薬品化学と宇宙生命科学を塗り替えた世界的金字塔を最高峰の学術英語で徹底解剖。",
    "source_name": "Jiji Press & Nature Chemistry (時事通信・ストックホルム特報 / Nobel Prize Committee Announcement)",
    "source_media_key": "jiji",
    "source_url": "https://www.jiji.com/jc/article?k=soai-reaction-nobel-chemistry-2026",
    "path": "science/soai-reaction-nobel-chemistry/index.html",
    "image": "https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "esports-highschool-education",
    "category": "entertainment",
    "category_label": "ENTERTAINMENT & EDUCATION • 教育工学・新世代部活動",
    "date": "2026-10-09",
    "title": "From Gaming to Graduation: High School Esports Programs Boost Teamwork and Digital Literacy",
    "headline_ja": "放課後ゲームから教育の最前線へ：高校の「eスポーツ部」が育むチームワークとデジタルリテラシー",
    "subhead": "単なる娯楽から学校教育の新たな柱へ。全国高校eスポーツ選手権の広がりと、戦略的思考力を養う教育効果を英語で探る。",
    "lead_snippet": "単なる娯楽から学校教育の新たな柱へ。全国高校eスポーツ選手権の広がりと、戦略的思考力を養う教育効果を英語で探る。",
    "source_name": "GetNews Japan & Yahoo! News (ガジェット通信・Yahoo!教育特集)",
    "source_media_key": "getnews",
    "source_url": "https://getnews.jp/archives/esports-highschool-education",
    "path": "entertainment/esports-highschool-education/index.html",
    "image": "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "global-plastics-treaty-negotiations",
    "category": "world",
    "category_label": "WORLD & ENVIRONMENT • 国連環境交渉・国際環境法",
    "date": "2026-10-09",
    "title": "A Binding Mandate for the Oceans: UN Delegates Convene to Finalize Global Plastics Treaty",
    "headline_ja": "地球規模の海洋プラスチック条約最終交渉：法的拘束力を持つ国際協定の締結へ",
    "subhead": "海洋汚染とマイクロプラスチックの根絶を目指す国連交渉。産油国と環境保護国の利害対立を国際法・環境外交の英語で読み解く。",
    "lead_snippet": "海洋汚染とマイクロプラスチックの根絶を目指す国連交渉。産油国と環境保護国の利害対立を国際法・環境外交の英語で読み解く。",
    "source_name": "Jiji Press & UN News (時事通信・ジュネーブ特報 / 国連環境総会)",
    "source_media_key": "jiji",
    "source_url": "https://www.jiji.com/jc/article?k=global-plastics-treaty-un",
    "path": "world/global-plastics-treaty-negotiations/index.html",
    "image": "https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "cashless-society-local-bus-crisis",
    "category": "society",
    "category_label": "SOCIETY & TRANSPORT • 公共交通とデジタル格差",
    "date": "2026-10-09",
    "title": "The Friction of Going Cashless: Rural Transit Systems Struggle with Fare Modernization",
    "headline_ja": "完全キャッシュレス化の波と地方の戸惑い：路線バスの運賃改編と高齢社会のデジタル格差",
    "subhead": "小銭の両替廃止や完全キャッシュレス決済の導入が進む一方、高齢者や通学児童の取り残しが課題に。交通権とデジタル化の摩擦を検証。",
    "lead_snippet": "小銭の両替廃止や完全キャッシュレス決済の導入が進む一方、高齢者や通学児童の取り残しが課題に。交通権とデジタル化の摩擦を検証。",
    "source_name": "Yahoo! News Japan & Jiji Press (Yahoo!ニュース解説 / 時事通信社会部)",
    "source_media_key": "yahoo",
    "source_url": "https://news.yahoo.co.jp/articles/cashless-bus-transit-crisis",
    "path": "society/cashless-society-local-bus-crisis/index.html",
    "image": "https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "perovskite-solar-cells-commercialization",
    "category": "science",
    "category_label": "SCIENCE & CLEAN TECH • 次世代エネルギー・材料工学",
    "date": "2026-10-09",
    "title": "Bending the Light: Japan Accelerates Commercial Rollout of Perovskite Solar Cells",
    "headline_ja": "曲がる太陽電池「ペロブスカイト」の社会実装：日本発の次世代クリーンエネルギー革命",
    "subhead": "ビル壁面や曲面にも設置可能なペロブスカイト太陽電池。主原料ヨウ素の世界的産出国である日本が世界標準を狙う技術開発を精読。",
    "lead_snippet": "ビル壁面や曲面にも設置可能なペロブスカイト太陽電池。主原料ヨウ素の世界的産出国である日本が世界標準を狙う技術開発を精読。",
    "source_name": "Jiji Press & Nikkei Science (時事通信先端技術特報 / 経済産業省エネルギー庁)",
    "source_media_key": "jiji",
    "source_url": "https://www.jiji.com/jc/article?k=perovskite-solar-cells-japan",
    "path": "science/perovskite-solar-cells-commercialization/index.html",
    "image": "https://images.unsplash.com/photo-1509391365360-2e959784a276?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "space-debris-corporate-liability",
    "category": "law",
    "category_label": "LAW & AEROSPACE • 宇宙法・企業賠償責任",
    "date": "2026-10-09",
    "title": "Orbital Gridlock: Legal Jurisdictions Clash Over Corporate Liability for Space Debris",
    "headline_ja": "宇宙ゴミ（スペースデブリ）の企業賠償責任：軌道混雑が生む宇宙法の新フロンティア",
    "subhead": "メガコンステレーション衛星の急増で衝突リスクが激増。宇宙条約（Outer Space Treaty）の限界と民間企業の責任法理を考察。",
    "lead_snippet": "メガコンステレーション衛星の急増で衝突リスクが激増。宇宙条約（Outer Space Treaty）の限界と民間企業の責任法理を考察。",
    "source_name": "Financial Times & Jiji Press (FT法務特報 / 国際宇宙法学会)",
    "source_media_key": "ft",
    "source_url": "https://www.ft.com/content/space-debris-liability-law",
    "path": "law/space-debris-corporate-liability/index.html",
    "image": "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "handwriting-cognitive-benefits",
    "category": "culture",
    "category_label": "CULTURE & NEUROSCIENCE • 認知心理学・文字文化",
    "date": "2026-10-09",
    "title": "The Pen Still Rules the Brain: Neuroscientists Reaffirm Cognitive Superiority of Handwriting",
    "headline_ja": "手書きが脳を覚醒させる：神経科学が実証したタイピングを超える記憶定着と創造性",
    "subhead": "タブレット学習が広がる今こそ見直される「手書き」の価値。脳波測定実験から明らかになった脳内ネットワークの活性化を精読。",
    "lead_snippet": "タブレット学習が広がる今こそ見直される「手書き」の価値。脳波測定実験から明らかになった脳内ネットワークの活性化を精読。",
    "source_name": "TIME Magazine & Frontiers in Psychology (TIME科学・教育特集)",
    "source_media_key": "time",
    "source_url": "https://time.com/handwriting-brain-connectivity-study",
    "path": "culture/handwriting-cognitive-benefits/index.html",
    "image": "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "remote-work-suburban-revitalization",
    "category": "society",
    "category_label": "SOCIETY & URBAN PLANNING • 都市社会学・地域創生",
    "date": "2026-10-09",
    "title": "Beyond the Megacity: How Hybrid Work Is Quietly Rebuilding Japan's Regional Towns",
    "headline_ja": "首都圏一極集中からの脱却：ハイブリッドワークが静かに後押しする地方移住と空き家再生",
    "subhead": "完全出社回帰でも完全フルリモートでもない「週2日通勤圏」。地方都市に移住した子育て世代が拓く地域活性化の新たな潮流。",
    "lead_snippet": "完全出社回帰でも完全フルリモートでもない「週2日通勤圏」。地方都市に移住した子育て世代が拓く地域活性化の新たな潮流。",
    "source_name": "Yahoo! News Japan (Yahoo!ニュース特報 / 国土交通省地域振興レポート)",
    "source_media_key": "yahoo",
    "source_url": "https://news.yahoo.co.jp/articles/hybrid-work-rural-revitalization",
    "path": "society/remote-work-suburban-revitalization/index.html",
    "image": "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "ai-music-copyright-royalties",
    "category": "entertainment",
    "category_label": "ENTERTAINMENT & IP LAW • 知的財産権・生成AI音楽",
    "date": "2026-10-09",
    "title": "Harmony or Theft? The Global Music Industry Demands Fair Royalties from Generative AI",
    "headline_ja": "調和か盗用か：生成AI楽曲の急増と世界音楽業界が求める著作権対価の新ルール",
    "subhead": "有名アーティストの声を再現したAI楽曲がストリーミングで数百万回再生。クリエイターの権利と技術革新のせめぎ合いを読み解く。",
    "lead_snippet": "有名アーティストの声を再現したAI楽曲がストリーミングで数百万回再生。クリエイターの権利と技術革新のせめぎ合いを読み解く。",
    "source_name": "GetNews Japan & Billboard (ガジェット通信・Billboardエンタメ特報)",
    "source_media_key": "getnews",
    "source_url": "https://getnews.jp/archives/ai-music-copyright-royalties",
    "path": "entertainment/ai-music-copyright-royalties/index.html",
    "image": "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "ai-energy-nuclear-data-centers",
    "category": "world",
    "category_label": "WORLD & ENERGY • 地政学・エネルギー安全保障",
    "date": "2026-10-09",
    "title": "Powering the AI Surge: Tech Giants Turn to Nuclear Energy to Feed Insatiable Data Centers",
    "headline_ja": "AI時代の電力危機：巨大テック企業がデータセンターの脱炭素電源に「小型原子力」を選ぶ理由",
    "subhead": "生成AIの計算処理に必要な電力消費が激増。24時間安定したゼロエミッション電力を求め、原子力発電の再評価が進む地政学的背景。",
    "lead_snippet": "生成AIの計算処理に必要な電力消費が激増。24時間安定したゼロエミッション電力を求め、原子力発電の再評価が進む地政学的背景。",
    "source_name": "Reuters & Jiji Press (ロイター・時事通信シリコンバレー特派)",
    "source_media_key": "jiji",
    "source_url": "https://www.jiji.com/jc/article?k=ai-nuclear-data-centers",
    "path": "world/ai-energy-nuclear-data-centers/index.html",
    "image": "https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "pnas-ai-biodiversity-monitoring",
    "category": "science",
    "category_label": "SCIENCE & COMPUTATIONAL ECOLOGY • 計算生態学・AI環境モニタリング",
    "date": "2026-10-10",
    "title": "Machine Learning Extracts Planetary Ecology Signals from Crowdsourced Naturalist Repositories",
    "headline_ja": "市民科学ビッグデータから地球規模の生態変動シグナルを抽出：PNAS最新研究が示すAIと環境観測の融合",
    "subhead": "世界中の愛好家が投稿する膨大な野鳥や植物の観察記録から、深層学習が微細な気候適応パターンを高精度に検出。保全生態学の新たな地平を英語で精読。",
    "lead_snippet": "世界中の愛好家が投稿する膨大な野鳥や植物の観察記録から、深層学習が微細な気候適応パターンを高精度に検出。保全生態学の新たな地平を英語で精読。",
    "source_name": "PNAS & Science (Oct 9, 2026)",
    "source_media_key": "nature",
    "source_url": "https://www.science.org/doi/10.1126/science.adi2026",
    "path": "science/pnas-ai-biodiversity-monitoring/index.html",
    "image": "https://images.unsplash.com/photo-1470240731273-7821a6eeb6bd?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "wwf-living-planet-biodiversity-collapse",
    "category": "science",
    "category_label": "ENVIRONMENT & CONSERVATION • 生態系保全・地球生命報告",
    "date": "2026-10-10",
    "title": "Living Planet Report 2026: Catastrophic 73% Decline in Monitored Wildlife and the Urgent Mandate for Agronomic Transition",
    "headline_ja": "野生脊椎動物73%激減の衝撃：WWF『生きている地球レポート2026』が突きつける食料システム転換の緊急性",
    "subhead": "半世紀で野生動物の個体群が4分の1以下に。淡水生態系の急激な崩壊と、持続可能な農業・サプライチェーン改革へのロードマップを科学英語で読み解く。",
    "lead_snippet": "半世紀で野生動物の個体群が4分の1以下に。淡水生態系の急激な崩壊と、持続可能な農業・サプライチェーン改革へのロードマップを科学英語で読み解く。",
    "source_name": "The Guardian & WWF Science (Oct 9, 2026)",
    "source_media_key": "the-guardian",
    "source_url": "https://www.theguardian.com/environment/2026/oct/09/living-planet-report-wildlife-decline",
    "path": "science/wwf-living-planet-biodiversity-collapse/index.html",
    "image": "https://images.unsplash.com/photo-1534567153574-2b12153a87f0?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "commercial-fusion-reactor-engineering",
    "category": "science",
    "category_label": "ENERGY PHYSICS & ENGINEERING • 核融合工学・次世代エネルギー",
    "date": "2026-10-10",
    "title": "High-Temperature Superconducting Magnets and the Industrialization of Commercial Magnetic Confinement Fusion",
    "headline_ja": "高温超電導磁石が切り拓く商業核融合の産業化：ボストン国際サミットが示す工学的現実味",
    "subhead": "「地上に太陽をつくる」核融合発電が、物理実験から商業プラント設計の段階へ。希土類バリウム銅酸化物（REBCO）磁石の量産と規制調和の最前線。",
    "lead_snippet": "「地上に太陽をつくる」核融合発電が、物理実験から商業プラント設計の段階へ。希土類バリウム銅酸化物（REBCO）磁石の量産と規制調和の最前線。",
    "source_name": "Reuters Science & MIT Tech Review (Oct 9, 2026)",
    "source_media_key": "reuters",
    "source_url": "https://www.reuters.com/business/energy/fusion-energy-commercialization-summit-2026",
    "path": "science/commercial-fusion-reactor-engineering/index.html",
    "image": "https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "food-sales-tax-cut-income-benefits",
    "category": "society",
    "category_label": "FISCAL POLICY & SOCIAL WELFARE • 財政政策・家計支援",
    "date": "2026-10-10",
    "title": "Cabinet Approves Historic Food Sales Tax Reduction and Dynamic Income-Linked Subsidy Matrix",
    "headline_ja": "政府、食料品消費税1%減税法案と所得連動型給付制度を閣議決定：生活防衛と財政健全化の狭間",
    "subhead": "物価高騰に直面する家計を守るため、食料品税率を2027年春から2年間大幅引き下げへ。低所得層への迅速な現金給付と財政規律を巡る国会論戦を英語で読む。",
    "lead_snippet": "物価高騰に直面する家計を守るため、食料品税率を2027年春から2年間大幅引き下げへ。低所得層への迅速な現金給付と財政規律を巡る国会論戦を英語で読む。",
    "source_name": "Jiji Press & Yahoo! News Japan (Oct 9, 2026)",
    "source_media_key": "jiji",
    "source_url": "https://www.jiji.com/jc/article?k=2026100900123",
    "path": "society/food-sales-tax-cut-income-benefits/index.html",
    "image": "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "dementia-smart-home-minder-system",
    "category": "society",
    "category_label": "GERONTOLOGY & DIGITAL CARE • 高齢社会・在宅ケア技術",
    "date": "2026-10-10",
    "title": "Ambient Sensor Telemetry and the 'Minder' Digital Safety Net: Prolonging Autonomous Living in Dementia Care",
    "headline_ja": "環境センサー遠隔監視と『Minder』システム：認知症高齢者の在宅自立支援がもたらす介護の革新",
    "subhead": "カメラではなく温度・開閉センサーで生活リズムを見守る最新医療技術。家族の介護負担を軽減し、尊厳ある住み慣れた自宅での生活を支える英国の大規模実証研究。",
    "lead_snippet": "カメラではなく温度・開閉センサーで生活リズムを見守る最新医療技術。家族の介護負担を軽減し、尊厳ある住み慣れた自宅での生活を支える英国の大規模実証研究。",
    "source_name": "UK Dementia Research Institute & The Guardian (Oct 9, 2026)",
    "source_media_key": "the-guardian",
    "source_url": "https://www.theguardian.com/society/2026/oct/09/minder-dementia-smart-home-care",
    "path": "society/dementia-smart-home-minder-system/index.html",
    "image": "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "ministerial-discretion-budget-allocation",
    "category": "society",
    "category_label": "GOVERNANCE & POLITICAL ETHICS • 政治倫理・公共事業配分",
    "date": "2026-10-10",
    "title": "Public Infrastructure Allocation and the Norms of Cabinet Neutrality: Political Scrutiny Over Regional Road Subsidies",
    "headline_ja": "公共インフラ予算配分と閣僚の中立性規範：地方道路補助金発言を巡る政治倫理と説明責任",
    "subhead": "選挙支援の有無で道路予算の配分を差別化したとされる閣僚発言が国会で猛反発。公共事業の配分基準、行政の公平性、そして政治的説明責任の境界線を英語で考察。",
    "lead_snippet": "選挙支援の有無で道路予算の配分を差別化したとされる閣僚発言が国会で猛反発。公共事業の配分基準、行政の公平性、そして政治的説明責任の境界線を英語で考察。",
    "source_name": "Jiji Press & Yahoo! News Japan (Oct 10, 2026)",
    "source_media_key": "jiji",
    "source_url": "https://www.jiji.com/jc/article?k=2026101000234",
    "path": "society/ministerial-discretion-budget-allocation/index.html",
    "image": "https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "highschool-endurance-walking-tradition",
    "category": "society",
    "category_label": "PEDAGOGY & PHYSICAL CULTURE • 学校教育・伝統身体文化",
    "date": "2026-10-10",
    "title": "The Endurance Pedagogy: Historical Continuity, Physical Resilience, and Community Solidarity in Japanese High School Marathons",
    "headline_ja": "伝統行事『強歩大会』の教育人間学：長距離踏破が育む青少年の忍耐力と地域社会の絆",
    "subhead": "夜を徹して数十キロを歩き抜く高校の伝統行事。効率性と安全管理が最優先される時代において、あえて過酷な身体体験を共有する教育的意義を多角的に検証。",
    "lead_snippet": "夜を徹して数十キロを歩き抜く高校の伝統行事。効率性と安全管理が最優先される時代において、あえて過酷な身体体験を共有する教育的意義を多角的に検証。",
    "source_name": "Yahoo! News Japan (Oct 9, 2026)",
    "source_media_key": "yahoo",
    "source_url": "https://news.yahoo.co.jp/articles/kyodo-kyoho-taikai-2026",
    "path": "society/highschool-endurance-walking-tradition/index.html",
    "image": "https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "experiential-judicial-education-youth",
    "category": "society",
    "category_label": "CIVICS & JUDICIAL PEDAGOGY • 法教育・主権者教育",
    "date": "2026-10-10",
    "title": "Inoculating Democratic Deliberation: Experiential Mock Trials and Secondary School Judicial Pedagogy",
    "headline_ja": "法教育と主権者意識の覚醒：中高生向け模擬裁判プログラムが育む論理的批判力と司法への信頼",
    "subhead": "弁護士や裁判官の指導のもと、実際の刑事事件記録をもとに無罪・有罪を議論する生徒たち。裁判員制度時代におけるアクティブラーニングと民主的対話力の育成。",
    "lead_snippet": "弁護士や裁判官の指導のもと、実際の刑事事件記録をもとに無罪・有罪を議論する生徒たち。裁判員制度時代におけるアクティブラーニングと民主的対話力の育成。",
    "source_name": "Yahoo! News Japan & Legal Education Association (Oct 9, 2026)",
    "source_media_key": "yahoo",
    "source_url": "https://news.yahoo.co.jp/articles/legal-education-mock-trials-2026",
    "path": "society/experiential-judicial-education-youth/index.html",
    "image": "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "ukraine-drone-strike-yandex-ai-datacenter",
    "category": "world",
    "category_label": "GEOPOLITICS & CYBER WARFARE • 現代戦・インフラ防衛",
    "date": "2026-10-10",
    "title": "Asymmetric Warfare Reaches the Compute Layer: Long-Range Drone Strikes on Sovereign AI Infrastructure",
    "headline_ja": "非対称戦争が到達した計算資源インフラ：ロシア大手Yandex AIデータセンターへのドローン攻撃と現代戦の変容",
    "subhead": "物理的爆薬を搭載した自爆ドローンが、敵国のディープラーニング基盤とクラウド中枢を直撃。軍民両用（デュアルユース）技術をめぐる新たな戦場力学を英語で精読。",
    "lead_snippet": "物理的爆薬を搭載した自爆ドローンが、敵国のディープラーニング基盤とクラウド中枢を直撃。軍民両用（デュアルユース）技術をめぐる新たな戦場力学を英語で精読。",
    "source_name": "Reuters & Al Jazeera (Oct 9, 2026)",
    "source_media_key": "reuters",
    "source_url": "https://www.reuters.com/world/europe/ukraine-drone-strike-yandex-datacenter-2026",
    "path": "world/ukraine-drone-strike-yandex-ai-datacenter/index.html",
    "image": "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "white-house-press-secretary-zacharias",
    "category": "world",
    "category_label": "US POLITICS & MEDIA • 米国政治・メディア戦略",
    "date": "2026-10-10",
    "title": "Executive Communications in a Polarized Media Sphere: The Appointment of White House Press Secretary Katie Zacharias",
    "headline_ja": "分断するメディア環境と政権広報戦略：トランプ米大統領、新大統領報道官に保守系論客ザカリア氏を指名",
    "subhead": "ホワイトハウスの「顔」となる報道官の電撃交代。伝統的プレスクラブへの対峙、直接配信プラットフォームの重用、そして大統領選を見据えた情報統制の変容を英語で読み解く。",
    "lead_snippet": "ホワイトハウスの「顔」となる報道官の電撃交代。伝統的プレスクラブへの対峙、直接配信プラットフォームの重用、そして大統領選を見据えた情報統制の変容を英語で読み解く。",
    "source_name": "Reuters & AP News (Oct 10, 2026)",
    "source_media_key": "reuters",
    "source_url": "https://www.reuters.com/world/us/white-house-appoints-katie-zacharias-press-secretary-2026",
    "path": "world/white-house-press-secretary-zacharias/index.html",
    "image": "https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "cop31-antalya-climate-finance-negotiations",
    "category": "world",
    "category_label": "INTERNATIONAL DIPLOMACY & CLIMATE • 国際気候交渉・金融枠組み",
    "date": "2026-10-10",
    "title": "The Antalya Modalities: Mobilizing Sovereign Balance Sheets and Loss-and-Damage Architecture Ahead of COP31",
    "headline_ja": "COP31アンタルヤ会議への道：気候資金拠出目標と『損失と損害』基金の運用枠組みを巡る南北対立",
    "subhead": "トルコ・アンタルヤで開催予定の国連気候変動枠組条約第31回締約国会議。数千億ドル規模の資金調達義務化と途上国の気候被害補償を巡る激動の外交交渉を英語で精読。",
    "lead_snippet": "トルコ・アンタルヤで開催予定の国連気候変動枠組条約第31回締約国会議。数千億ドル規模の資金調達義務化と途上国の気候被害補償を巡る激動の外交交渉を英語で精読。",
    "source_name": "Reuters & UN Climate News (Oct 9, 2026)",
    "source_media_key": "reuters",
    "source_url": "https://www.reuters.com/business/environment/cop31-climate-finance-negotiations-antalya-2026",
    "path": "world/cop31-antalya-climate-finance-negotiations/index.html",
    "image": "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "horizon-europe-biodiversity-digital-transition",
    "category": "world",
    "category_label": "EUROPEAN POLICY & TECH • 欧州科学政策・デジタル脱炭素",
    "date": "2026-10-10",
    "title": "European Commission Deploys €230m Horizon Call to Decouple Digital Industry from Ecological Degradation",
    "headline_ja": "欧州委員会、2.3億ユーロの研究助成開始：デジタル産業の電力消費抑制と生物多様性保全の両立",
    "subhead": "急速に膨張するAIデータセンターの電力・水消費をいかに抑えるか。欧州連合（EU）が巨額のHorizon助成金を投じ、循環型半導体と生態系修復技術を加速。",
    "lead_snippet": "急速に膨張するAIデータセンターの電力・水消費をいかに抑えるか。欧州連合（EU）が巨額のHorizon助成金を投じ、循環型半導体と生態系修復技術を加速。",
    "source_name": "European Commission & The Guardian (Oct 9, 2026)",
    "source_media_key": "the-guardian",
    "source_url": "https://www.theguardian.com/world/2026/oct/09/eu-horizon-digital-biodiversity-fund",
    "path": "world/horizon-europe-biodiversity-digital-transition/index.html",
    "image": "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "red-sea-maritime-corridor-commercial-convoy",
    "category": "world",
    "category_label": "MARITIME GEOPOLITICS & TRADE • 海洋安全保障・国際物流",
    "date": "2026-10-10",
    "title": "Naval Escort Architectures and Commercial Underwriting: Securing the Bab-el-Mandeb Maritime Bottleneck",
    "headline_ja": "バブ・エル・マンデブ海峡の航路防衛：多国籍護衛艦艇アーキテクチャと海上保険料率の地政学",
    "subhead": "紅海入口での対艦ミサイル・自爆無人艇の脅威に対し、有志連合による商船護衛体制が再編。スエズ運河を迂回する喜望峰ルートとの運賃コスト比較を英語で読み解く。",
    "lead_snippet": "紅海入口での対艦ミサイル・自爆無人艇の脅威に対し、有志連合による商船護衛体制が再編。スエズ運河を迂回する喜望峰ルートとの運賃コスト比較を英語で読み解く。",
    "source_name": "Financial Times & Reuters (Oct 9, 2026)",
    "source_media_key": "ft",
    "source_url": "https://www.ft.com/content/red-sea-shipping-corridor-security-2026",
    "path": "world/red-sea-maritime-corridor-commercial-convoy/index.html",
    "image": "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "supreme-court-sheet-music-piracy-ruling",
    "category": "law",
    "category_label": "INTELLECTUAL PROPERTY & TORT • 知的財産法・不正競争防止法",
    "date": "2026-10-10",
    "title": "Supreme Court Affirms ¥169m Damages for Unlicensed Tablature Aggregation Under Unfair Competition Norms",
    "headline_ja": "最高裁、模倣楽譜データ無断公開サイトに1億6900万円の損害賠償を確定：著作隣接権と不正競争防止法",
    "subhead": "著作権法上の創作性が認められにくい採譜データであっても、他者の投下資本や労力による成果をフリーライドする行為は不法行為を構成。最高裁判決の法理を英語で精読。",
    "lead_snippet": "著作権法上の創作性が認められにくい採譜データであっても、他者の投下資本や労力による成果をフリーライドする行為は不法行為を構成。最高裁判決の法理を英語で精読。",
    "source_name": "Jiji Press & Yahoo! News Japan (Oct 9, 2026)",
    "source_media_key": "jiji",
    "source_url": "https://www.jiji.com/jc/article?k=2026100900345",
    "path": "law/supreme-court-sheet-music-piracy-ruling/index.html",
    "image": "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "japan-icc-sanctions-rule-of-law",
    "category": "law",
    "category_label": "INTERNATIONAL LAW & JURISPRUDENCE • 国際法・多国間司法秩序",
    "date": "2026-10-10",
    "title": "Defending Multilateral Jurisprudence: Japan Voices Grave Concern Over Unilateral Sanctions Against the ICC",
    "headline_ja": "多国間司法制度の擁護：日本政府、米国の国際刑事裁判所（ICC）制裁に深刻な懸念を表明",
    "subhead": "赤根智子裁判官が所長を務めるICCに対し、米議会が制裁を科す動きに日本が明確な反対姿勢を表明。「法の支配」と日米同盟の狭間で下された外交判断の法哲学的意義。",
    "lead_snippet": "赤根智子裁判官が所長を務めるICCに対し、米議会が制裁を科す動きに日本が明確な反対姿勢を表明。「法の支配」と日米同盟の狭間で下された外交判断の法哲学的意義。",
    "source_name": "Jiji Press & Yahoo! News Japan (Oct 9, 2026)",
    "source_media_key": "jiji",
    "source_url": "https://www.jiji.com/jc/article?k=2026100900456",
    "path": "law/japan-icc-sanctions-rule-of-law/index.html",
    "image": "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "okinawa-assembly-sofa-revision-resolution",
    "category": "law",
    "category_label": "CONSTITUTIONAL & TREATY LAW • 条約法・地位協定",
    "date": "2026-10-10",
    "title": "Extraterritorial Jurisdiction and Sovereign Parity: Okinawa Prefectural Assembly Demands SOFA Reform",
    "headline_ja": "治外法権的特権の是正と主権の平等：沖縄県議会、日米地位協定の抜本改定を求める意見書・決議を可決",
    "subhead": "米海兵隊員による事件を受け、基地特権や初動捜査権の不均衡を是正するよう国と米政府に要請。主権国家としての裁判管轄権と日米安保条約の課題を英語で読み解く。",
    "lead_snippet": "米海兵隊員による事件を受け、基地特権や初動捜査権の不均衡を是正するよう国と米政府に要請。主権国家としての裁判管轄権と日米安保条約の課題を英語で読み解く。",
    "source_name": "Jiji Press & Yahoo! News Japan (Oct 9, 2026)",
    "source_media_key": "jiji",
    "source_url": "https://www.jiji.com/jc/article?k=2026100900567",
    "path": "law/okinawa-assembly-sofa-revision-resolution/index.html",
    "image": "https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "autonomous-fleet-criminal-liability",
    "category": "law",
    "category_label": "TORT & ROBOTIC LIABILITY • 自動運転・刑事過失責任",
    "date": "2026-10-10",
    "title": "Apportioning Culpability in Sensor Dropout: High Court Scrutinizes Fleet Operator Negligence in Autonomous Transit",
    "headline_ja": "センサー故障時の過失帰属：自動運転運行会社に対する刑事過失責任と法人の注意義務を巡る高等裁判所判決",
    "subhead": "濃霧でのLiDAR反射異常による衝突事故。AIアルゴリズムの予見可能性と、遠隔監視オペレーターの介入義務を巡る法哲学的判断。ロボット時代の過失責任論を英語で精読。",
    "lead_snippet": "濃霧でのLiDAR反射異常による衝突事故。AIアルゴリズムの予見可能性と、遠隔監視オペレーターの介入義務を巡る法哲学的判断。ロボット時代の過失責任論を英語で精読。",
    "source_name": "Financial Times & The Guardian (Oct 9, 2026)",
    "source_media_key": "ft",
    "source_url": "https://www.ft.com/content/autonomous-fleet-operator-liability-ruling-2026",
    "path": "law/autonomous-fleet-criminal-liability/index.html",
    "image": "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "clinical-ai-algorithmic-transparency-mandate",
    "category": "law",
    "category_label": "BIOETHICS & AI REGULATION • 医療倫理・アルゴリズム開示義務",
    "date": "2026-10-10",
    "title": "The Right to Algorithmic Explanation: High Court Sets Precedent on Neural Model Disclosures in Oncology Trials",
    "headline_ja": "アルゴリズムの説明を受ける権利：がん治験における深層学習診断モデルの開示義務を認めた歴史的判決",
    "subhead": "AIによる投薬判断が患者の除外や治療法変更を決定した際、ブラックボックスであることを理由に説明を拒むことは違法。インフォームド・コンセントの現代的再定義を英語で読み解く。",
    "lead_snippet": "AIによる投薬判断が患者の除外や治療法変更を決定した際、ブラックボックスであることを理由に説明を拒むことは違法。インフォームド・コンセントの現代的再定義を英語で読み解く。",
    "source_name": "The Guardian & BMJ Health (Oct 9, 2026)",
    "source_media_key": "the-guardian",
    "source_url": "https://www.theguardian.com/law/2026/oct/09/high-court-ai-medical-algorithm-transparency-ruling",
    "path": "law/clinical-ai-algorithmic-transparency-mandate/index.html",
    "image": "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "tateyama-shugendo-faith-cinema",
    "category": "culture",
    "category_label": "RELIGIOUS ANTHROPOLOGY & CINEMA • 宗教人類学・山岳信仰映画",
    "date": "2026-10-10",
    "title": "Liminality, Purification, and Sacred Peaks: Mountain Asceticism in Contemporary Japanese Faith Cinema",
    "headline_ja": "境界性と魂の浄化：立山信仰と修験道の世界を描く新作映画『無明の橋』と現代の精神文化",
    "subhead": "日本三霊山・立山に息づく布橋灌頂会と他界観。物質的過剰とデジタル疲弊に苛まれる現代人が、峻厳な自然との身体的対峙を通じて魂の再生を求める映画美学を英語で精読。",
    "lead_snippet": "日本三霊山・立山に息づく布橋灌頂会と他界観。物質的過剰とデジタル疲弊に苛まれる現代人が、峻厳な自然との身体的対峙を通じて魂の再生を求める映画美学を英語で精読。",
    "source_name": "Yahoo! News Japan & Cinema Culture (Oct 9, 2026)",
    "source_media_key": "yahoo",
    "source_url": "https://news.yahoo.co.jp/articles/tateyama-cinema-faith-2026",
    "path": "culture/tateyama-shugendo-faith-cinema/index.html",
    "image": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "bbc-radio-overhaul-future-ideas",
    "category": "culture",
    "category_label": "MEDIA ANTHROPOLOGY & PUBLIC SPEECH • メディア論・公共言論",
    "date": "2026-10-10",
    "title": "The Architecture of Public Speech: BBC Retires Legacy Daytime Formats in Strategic Pivot to AI and Intellectual Culture",
    "headline_ja": "公共言論空間の再編：英BBC、長寿帯番組を終了し先端技術と思想文化の新番組へと刷新",
    "subhead": "半世紀続いた国民的情報番組『You and Yours』の幕引き。ポッドキャスト全盛と短縮化が進む時代に、公共放送があえて骨太な思想・テクノロジー深掘りへと舵を切る理由を英語で精読。",
    "lead_snippet": "半世紀続いた国民的情報番組『You and Yours』の幕引き。ポッドキャスト全盛と短縮化が進む時代に、公共放送があえて骨太な思想・テクノロジー深掘りへと舵を切る理由を英語で精読。",
    "source_name": "The Guardian (Oct 9, 2026)",
    "source_media_key": "the-guardian",
    "source_url": "https://www.theguardian.com/media/2026/oct/09/bbc-radio-4-you-and-yours-replacement-ai-ideas",
    "path": "culture/bbc-radio-overhaul-future-ideas/index.html",
    "image": "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "terroir-culinary-anthropology-okayama",
    "category": "culture",
    "category_label": "CULINARY ANTHROPOLOGY & HERITAGE • 食文化人類学・風土の継承",
    "date": "2026-10-10",
    "title": "The Taste of Place: Micro-Seasonality, Agrarian Heritage, and the Living Anthropology of Regional Gastronomy",
    "headline_ja": "風土を味わう文化人類学：岡山における郷土食材の再発見と味覚の記憶が紡ぐ地域再生",
    "subhead": "工業化された画一的なグローバル食生活に対し、地域の土壌と季節の恵みを再現する食文化イニシアチブ。古代米、発酵調味料、そして気候風土（テロワール）が織りなす生きた知恵を英語で読み解く。",
    "lead_snippet": "工業化された画一的なグローバル食生活に対し、地域の土壌と季節の恵みを再現する食文化イニシアチブ。古代米、発酵調味料、そして気候風土（テロワール）が織りなす生きた知恵を英語で読み解く。",
    "source_name": "Yahoo! News Japan (Oct 9, 2026)",
    "source_media_key": "yahoo",
    "source_url": "https://news.yahoo.co.jp/articles/okayama-terroir-gastronomy-2026",
    "path": "culture/terroir-culinary-anthropology-okayama/index.html",
    "image": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "soai-philosophical-lineage-curiosity",
    "category": "culture",
    "category_label": "PHILOSOPHY OF SCIENCE & BIOGRAPHY • 科学思想・ノーベル賞の系譜",
    "date": "2026-10-10",
    "title": "The Epistemic Virtue of Serendipity: Academic Rigor and the Intellectual Legacy of Kensou Soai",
    "headline_ja": "セレンディピティの認識論：ノーベル化学賞・相愛賢壮氏の歩みと研究室に息づく知的好奇心の思想史",
    "subhead": "広島の高校時代から始まった化学への情熱。教科書の常識を疑い、不斉合成における自己増殖現象を発見した不屈の研究精神と、学問の自由の尊さを英語で精読。",
    "lead_snippet": "広島の高校時代から始まった化学への情熱。教科書の常識を疑い、不斉合成における自己増殖現象を発見した不屈の研究精神と、学問の自由の尊さを英語で精読。",
    "source_name": "Jiji Press & Nature Chemistry (Oct 10, 2026)",
    "source_media_key": "jiji",
    "source_url": "https://www.jiji.com/jc/article?k=2026101000678",
    "path": "culture/soai-philosophical-lineage-curiosity/index.html",
    "image": "https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "public-libraries-civic-living-rooms",
    "category": "culture",
    "category_label": "URBAN SOCIOLOGY & CIVIC SPACE • 公共空間・サードプレイス論",
    "date": "2026-10-10",
    "title": "The Sanctuary of Shared Silence: Public Libraries as Non-Commercial Infrastructure in an Age of Hyper-Individualism",
    "headline_ja": "共有された静寂の聖域：ハイパー個人主義の時代における公共図書館と『買わなくてよい空間』の社会学",
    "subhead": "カフェもコワーキングスペースもお金がかかる都市生活において、何も買わずに誰でも滞在できる「サードプレイス」としての公立図書館。孤独を癒やす脱商品化空間を英語で読む。",
    "lead_snippet": "カフェもコワーキングスペースもお金がかかる都市生活において、何も買わずに誰でも滞在できる「サードプレイス」としての公立図書館。孤独を癒やす脱商品化空間を英語で読む。",
    "source_name": "TIME Magazine (Oct 9, 2026)",
    "source_media_key": "time",
    "source_url": "https://time.com/article/2026/10/09/public-libraries-third-places-loneliness",
    "path": "culture/public-libraries-civic-living-rooms/index.html",
    "image": "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "kyocera-ceramic-coating-vacuum-tumblers",
    "category": "entertainment",
    "category_label": "MATERIALS SCIENCE & CONSUMER TECH • 材料工学・ライフスタイル技術",
    "date": "2026-10-10",
    "title": "Eliminating Metallic Aftertaste: Advanced Ceramic Thin-Film Sintering in Consumer Insulated Drinkware",
    "headline_ja": "金属臭をゼロにする先端材料工学：京セラ、セラミック薄膜コーティングボトルの一般販売開始",
    "subhead": "コーヒーの繊細な酸味やスポーツドリンクの塩分で金属が溶け出す課題を解消。ファインセラミックスの微細焼結技術が日常のドリンクウェアを進化させる工学美学を英語で精読。",
    "lead_snippet": "コーヒーの繊細な酸味やスポーツドリンクの塩分で金属が溶け出す課題を解消。ファインセラミックスの微細焼結技術が日常のドリンクウェアを進化させる工学美学を英語で精読。",
    "source_name": "Kyodo News PR Wire & GetNews Japan (Oct 9, 2026)",
    "source_media_key": "getnews",
    "source_url": "https://getnews.jp/archives/kyocera-ceramic-bottle-general-sale-2026",
    "path": "entertainment/kyocera-ceramic-coating-vacuum-tumblers/index.html",
    "image": "https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "telecom-sales-unauthorized-access-arrests",
    "category": "entertainment",
    "category_label": "CYBER LAW & TELECOM REGULATION • 通信倫理・サイバー犯罪取締",
    "date": "2026-10-10",
    "title": "Aggressive Telemarketing and Unauthorized Credential Access: Metropolitan Police Clampdown on Broadband Agency Fraud",
    "headline_ja": "強引な光回線勧誘と不正アクセス：警視庁、通信販売代理店営業員を逮捕と通信販売網の規律",
    "subhead": "他人のID・パスワードを不正利用して契約者情報を盗み見、強引な電話営業で乗り換えを迫る手口。電気通信事業法と不正アクセス禁止法の適用厳罰化を英語で精読。",
    "lead_snippet": "他人のID・パスワードを不正利用して契約者情報を盗み見、強引な電話営業で乗り換えを迫る手口。電気通信事業法と不正アクセス禁止法の適用厳罰化を英語で精読。",
    "source_name": "Jiji Press & Yahoo! News Japan (Oct 9, 2026)",
    "source_media_key": "jiji",
    "source_url": "https://www.jiji.com/jc/article?k=2026100900789",
    "path": "entertainment/telecom-sales-unauthorized-access-arrests/index.html",
    "image": "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "ultrasonic-midair-haptics-xr-gaming",
    "category": "entertainment",
    "category_label": "EXTENDED REALITY & HAPTICS • XR空間音響・空中触覚工学",
    "date": "2026-10-10",
    "title": "Acoustic Radiation Pressure and Mid-Air Tactility: The Next Ergonomic Leap in Spatial Computing and XR",
    "headline_ja": "超音波放射圧が生む空中触覚：空間コンピューティングと次世代XRゲームの没入感フロンティア",
    "subhead": "コントローラーも手袋も装着せず、何もない空間で「仮想のボタンや感触」を肌で感じる。音波の物理学が生み出す次世代ハプティクス技術の最前線を英語で精読。",
    "lead_snippet": "コントローラーも手袋も装着せず、何もない空間で「仮想のボタンや感触」を肌で感じる。音波の物理学が生み出す次世代ハプティクス技術の最前線を英語で精読。",
    "source_name": "GetNews Japan & TechCrunch (Oct 9, 2026)",
    "source_media_key": "getnews",
    "source_url": "https://getnews.jp/archives/ultrasonic-midair-haptics-xr-2026",
    "path": "entertainment/ultrasonic-midair-haptics-xr-gaming/index.html",
    "image": "https://images.unsplash.com/photo-1592478411213-6153e4ebc07d?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "anime-voice-actors-generative-ai-compact",
    "category": "entertainment",
    "category_label": "CREATIVE ARTS & AI REGULATION • コンテンツ産業・声優権利保護",
    "date": "2026-10-10",
    "title": "Voice Synthesizer Licensing and the Preservation of Craft: Japanese Voice Actor Guilds Formulate Generative AI Standards",
    "headline_ja": "声の権利と表現の尊厳：声優団体による生成AI音声利用ガイドラインの制定とライセンス交渉",
    "subhead": "アニメの世界配信で急増する多言語AI吹き替えや無断ボイスクローン。声優の肖像権・実演家人格権を守りつつ、先端技術と共存するための業界ルールを英語で読み解く。",
    "lead_snippet": "アニメの世界配信で急増する多言語AI吹き替えや無断ボイスクローン。声優の肖像権・実演家人格権を守りつつ、先端技術と共存するための業界ルールを英語で読み解く。",
    "source_name": "GetNews Japan & Yahoo! News (Oct 9, 2026)",
    "source_media_key": "getnews",
    "source_url": "https://getnews.jp/archives/anime-voice-actors-ai-guidelines-2026",
    "path": "entertainment/anime-voice-actors-generative-ai-compact/index.html",
    "image": "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=1000&auto=format&fit=crop&q=80"
  },
  {
    "slug": "binaural-spatial-acoustics-concert-streaming",
    "category": "entertainment",
    "category_label": "ACOUSTIC ENGINEERING & MUSIC • 音響工学・クラシック生配信",
    "date": "2026-10-10",
    "title": "Head-Related Transfer Functions and Acoustic Telepresence: The Engineering of Live Symphonic Binaural Streaming",
    "headline_ja": "頭部伝達関数（HRTF）が再現するコンサートホールの臨場感：オーケストラ生配信のバイノーラル音響工学",
    "subhead": "自宅の普通のイヤホンで、あたかも特等席に座っているかのような音の立体感を再現。ダミーヘッドマイクとリアルタイム空間音響演算がクラシック鑑賞を一変させる技術を英語で精読。",
    "lead_snippet": "自宅の普通のイヤホンで、あたかも特等席に座っているかのような音の立体感を再現。ダミーヘッドマイクとリアルタイム空間音響演算がクラシック鑑賞を一変させる技術を英語で精読。",
    "source_name": "GetNews Japan & SoundOnSound (Oct 9, 2026)",
    "source_media_key": "getnews",
    "source_url": "https://getnews.jp/archives/binaural-symphony-live-streaming-2026",
    "path": "entertainment/binaural-spatial-acoustics-concert-streaming/index.html",
    "image": "https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=1000&auto=format&fit=crop&q=80"
  }
];

const EDITIONS = {
  "2026-10-10": {
    "dateStr": "Saturday October 10 2026",
    "editionLabel": "2026年10月10日 (土) 号 【本日最新版・全30記事】",
    "tagline": "特集：ノーベル化学賞硤合教授・坂口特任教授免疫革新・AIデータセンター・食料品消費税減税",
    "topLeadSlug": "soai-reaction-nobel-chemistry",
    "subLeadSlugs": [
      "regulatory-t-cells-nobel-breakthrough",
      "food-sales-tax-cut-income-benefits",
      "ukraine-drone-strike-yandex-ai-datacenter"
    ],
    "leftDispatches": [
      "supreme-court-sheet-music-piracy-ruling",
      "japan-icc-sanctions-rule-of-law",
      "pnas-ai-biodiversity-monitoring",
      "kyocera-ceramic-coating-vacuum-tumblers"
    ],
    "rightDigestSlugs": [
      "wwf-living-planet-biodiversity-collapse",
      "commercial-fusion-reactor-engineering",
      "dementia-smart-home-minder-system",
      "white-house-press-secretary-zacharias",
      "cop31-antalya-climate-finance-negotiations",
      "okinawa-assembly-sofa-revision-resolution",
      "tateyama-shugendo-faith-cinema"
    ]
  },
  "2026-10-09": {
    "dateStr": "Friday October 9 2026",
    "editionLabel": "2026年10月9日 (金) 号 【バックナンバー】",
    "tagline": "特集：ノーベル賞日本人受賞ラッシュと次世代半導体・脱炭素の最前線",
    "topLeadSlug": "japan-semiconductor-revival-rapidus",
    "subLeadSlugs": [
      "smart-glasses-ai-privacy",
      "digital-school-backpack-reform"
    ],
    "leftDispatches": [
      "global-plastics-treaty-negotiations",
      "cashless-society-local-bus-crisis",
      "perovskite-solar-cells-commercialization"
    ],
    "rightDigestSlugs": [
      "space-debris-corporate-liability",
      "handwriting-cognitive-benefits",
      "remote-work-suburban-revitalization",
      "ai-music-copyright-royalties"
    ]
  },
  "2026-10-06": {
    "dateStr": "Tuesday October 6 2026",
    "editionLabel": "2026年10月6日 (火) 号 【バックナンバー】",
    "tagline": "特集：公共空間のイヤホン論争と都市の孤独・偶発的出会いの心理学",
    "topLeadSlug": "headphones-in-public",
    "subLeadSlugs": [
      "jeffrey-archer-obituary",
      "royal-security-judicial-review"
    ],
    "leftDispatches": [
      "air-defence-shield",
      "colorectal-cancer-under-50s",
      "raf-fairford-bomber-redeployment"
    ],
    "rightDigestSlugs": [
      "clarkson-business-red-tape",
      "inheritance-tax-reform-debate",
      "ai-pediatric-diagnosis-consent",
      "mediterranean-marine-heatwaves"
    ]
  },
  "2026-10-05": {
    "dateStr": "Monday October 5 2026",
    "editionLabel": "2026年10月5日 (月) 号 【バックナンバー】",
    "tagline": "特集：英国100億ポンド防衛シールド審議と司法審査・王室警護裁量",
    "topLeadSlug": "air-defence-shield",
    "subLeadSlugs": [
      "royal-security-judicial-review",
      "clarkson-business-red-tape"
    ],
    "leftDispatches": [
      "headphones-in-public",
      "inheritance-tax-reform-debate",
      "mediterranean-marine-heatwaves"
    ],
    "rightDigestSlugs": [
      "jeffrey-archer-obituary",
      "ai-pediatric-diagnosis-consent",
      "colorectal-cancer-under-50s",
      "raf-fairford-bomber-redeployment"
    ]
  },
  "2026-10-04": {
    "dateStr": "Sunday October 4 2026",
    "editionLabel": "2026年10月4日 (日) 号 【バックナンバー】",
    "tagline": "特集：50歳未満の大腸がん世界的急増と地中海深海熱波の生体ストレス",
    "topLeadSlug": "colorectal-cancer-under-50s",
    "subLeadSlugs": [
      "mediterranean-marine-heatwaves",
      "generative-ai-paleontology"
    ],
    "leftDispatches": [
      "ai-pediatric-diagnosis-consent",
      "psychology-casual-encounters",
      "inheritance-tax-reform-debate"
    ],
    "rightDigestSlugs": [
      "headphones-in-public",
      "air-defence-shield",
      "clarkson-business-red-tape",
      "jeffrey-archer-obituary"
    ]
  },
  "2026-10-03": {
    "dateStr": "Saturday October 3 2026",
    "editionLabel": "2026年10月3日 (土) 号 【バックナンバー】",
    "tagline": "特集：小児AI診断の親同意権と古生物学における生成ニューラルネットワーク",
    "topLeadSlug": "ai-pediatric-diagnosis-consent",
    "subLeadSlugs": [
      "generative-ai-paleontology",
      "royal-security-judicial-review"
    ],
    "leftDispatches": [
      "clarkson-business-red-tape",
      "colorectal-cancer-under-50s",
      "jeffrey-archer-obituary"
    ],
    "rightDigestSlugs": [
      "headphones-in-public",
      "mediterranean-marine-heatwaves",
      "psychology-casual-encounters",
      "inheritance-tax-reform-debate"
    ]
  },
  "2026-10-02": {
    "dateStr": "Friday October 2 2026",
    "editionLabel": "2026年10月2日 (金) 号 【バックナンバー】",
    "tagline": "特集：相続税改革と世代間格差の政治哲学・クラークソン英起業規制論",
    "topLeadSlug": "inheritance-tax-reform-debate",
    "subLeadSlugs": [
      "clarkson-business-red-tape",
      "psychology-casual-encounters"
    ],
    "leftDispatches": [
      "raf-fairford-bomber-redeployment",
      "royal-security-judicial-review",
      "generative-ai-paleontology"
    ],
    "rightDigestSlugs": [
      "air-defence-shield",
      "colorectal-cancer-under-50s",
      "headphones-in-public",
      "ai-pediatric-diagnosis-consent"
    ]
  },
  "2026-10-01": {
    "dateStr": "Thursday October 1 2026",
    "editionLabel": "2026年10月1日 (木) 号 【創刊バックナンバー】",
    "tagline": "特集：フェアフォード米戦略爆撃機再配置とジェフリー・アーチャー氏追悼",
    "topLeadSlug": "raf-fairford-bomber-redeployment",
    "subLeadSlugs": [
      "jeffrey-archer-obituary",
      "generative-ai-paleontology"
    ],
    "leftDispatches": [
      "air-defence-shield",
      "inheritance-tax-reform-debate",
      "mediterranean-marine-heatwaves"
    ],
    "rightDigestSlugs": [
      "clarkson-business-red-tape",
      "psychology-casual-encounters",
      "royal-security-judicial-review",
      "headphones-in-public"
    ]
  }
};
